In [1]:
import QUANTAXIS as QA
import pandas as pd
import tushare as ts
import numpy as np
# import TA-Lib as ta
import scipy.signal as signal
import matplotlib.pyplot as plt

In [2]:
one_stock_date = QA.QA_fetch_stock_day_adv('000001','2020-05-01','2020-08-22')
df_one_stock = one_stock_date.data
df_one_stock.head()
df_one_stock.droplevel(level=1,axis=0)

             open   high    low  close     volume        amount
date
2020-05-06  13.76  13.89  13.61  13.77  1008998.0  1.382727e+09
2020-05-07  13.76  13.76  13.60  13.69   662749.0  9.043495e+08
2020-05-08  13.76  14.02  13.68  13.95   934781.0  1.297925e+09
2020-05-11  13.92  14.13  13.90  14.00   612862.0  8.591566e+08
2020-05-12  13.95  14.05  13.72  13.79   558511.0  7.721095e+08
2020-05-13  13.75  13.78  13.53  13.63   640358.0  8.710620e+08
2020-05-14  13.55  13.59  13.22  13.30   944672.0  1.259441e+09
2020-05-15  13.39  13.43  13.14  13.23   756794.0  1.004313e+09
2020-05-18  13.20  13.34  13.12  13.20   637208.0  8.434797e+08
2020-05-19  13.41  13.45  13.27  13.36   600368.0  8.017556e+08
2020-05-20  13.38  13.62  13.27  13.51   690851.0  9.299289e+08
2020-05-21  13.52  13.57  13.36  13.40   552312.0  7.427971e+08
2020-05-22  13.33  13.34  12.92  12.92   856237.0  1.119433e+09
2020-05-25  12.97  12.98  12.76  12.96   410170.0  5.287693e+08
2020-05-26  13.02  13.07  12.94  13.04   396212.0  5.154518e+08
2020-05-27  13.05  13.19  12.96  13.00   482962.0  6.303059e+08
2020-05-28  12.87  13.18  12.81  13.07   960760.0  1.255227e+09
2020-05-29  13.01  13.04  12.92  13.00   457808.0  5.945021e+08
2020-06-01  13.10  13.39  13.08  13.32   882960.0  1.173619e+09
2020-06-02  13.29  13.63  13.28  13.55   883458.0  1.194376e+09
2020-06-03  13.64  13.88  13.50  13.54   956803.0  1.308782e+09
2020-06-04  13.53  13.64  13.41  13.57   583066.0  7.887076e+08
2020-06-05  13.60  13.62  13.43  13.59   383026.0  5.172321e+08
2020-06-08  13.68  13.85  13.58  13.62   585971.0  8.021158e+08
2020-06-09  13.64  13.73  13.53  13.67   474300.0  6.468958e+08
2020-06-10  13.71  13.71  13.40  13.49   580476.0  7.819958e+08
2020-06-11  13.38  13.39  13.00  13.08  1349039.0  1.774200e+09
2020-06-12  12.90  13.02  12.87  12.99  1030550.0  1.331619e+09
2020-06-15  12.85  12.97  12.80  12.82   660313.0  8.507675e+08
2020-06-16  12.90  12.99  12.86  12.89   718059.0  9.270437e+08
...           ...    ...    ...    ...        ...           ...
2020-07-13  14.70  15.08  14.50  14.89  1937160.0  2.871415e+09
2020-07-14  14.90  15.19  14.55  14.68  1953566.0  2.891774e+09
2020-07-15  14.78  14.86  14.23  14.27  2042562.0  2.947173e+09
2020-07-16  14.30  14.55  14.12  14.15  1930891.0  2.771496e+09
2020-07-17  14.17  14.28  13.95  14.14  1291346.0  1.821044e+09
2020-07-20  14.23  14.77  14.10  14.73  1979632.0  2.872758e+09
2020-07-21  14.68  14.68  14.40  14.49  1252865.0  1.815570e+09
2020-07-22  14.49  14.65  14.27  14.41  1312951.0  1.895447e+09
2020-07-23  14.24  14.29  13.81  14.01  2027525.0  2.838535e+09
2020-07-24  13.97  13.99  13.42  13.50  1830881.0  2.504647e+09
2020-07-27  13.67  13.68  13.10  13.24  1880653.0  2.497551e+09
2020-07-28  13.34  13.43  13.18  13.34  1217006.0  1.618090e+09
2020-07-29  13.35  13.63  13.21  13.54  1519580.0  2.043847e+09
2020-07-30  13.50  13.51  13.37  13.37   964067.0  1.294445e+09
2020-07-31  13.28  13.53  13.25  13.34  1165821.0  1.559068e+09
2020-08-03  13.47  13.62  13.43  13.59  1445096.0  1.954607e+09
2020-08-04  13.66  14.15  13.48  14.04  2445663.0  3.388510e+09
2020-08-05  13.82  13.85  13.62  13.76  1440203.0  1.980353e+09
2020-08-06  13.82  13.96  13.65  13.90  1352510.0  1.868047e+09
2020-08-07  13.80  13.90  13.62  13.70   988678.0  1.356306e+09
2020-08-10  13.67  14.02  13.62  13.95  1587710.0  2.208568e+09
2020-08-11  13.97  14.66  13.97  14.13  2603307.0  3.748037e+09
2020-08-12  14.21  14.50  14.15  14.38  1596811.0  2.287731e+09
2020-08-13  14.40  14.46  14.14  14.18   837261.0  1.190140e+09
2020-08-14  14.10  14.51  14.06  14.47  1103215.0  1.578544e+09
2020-08-17  14.60  15.35  14.55  15.19  3268027.0  4.923669e+09
2020-08-18  15.20  15.30  14.91  15.15  1350261.0  2.033478e+09
2020-08-19  15.11  15.35  14.96  15.10  1420928.0  2.154215e+09
2020-08-20  15.01  15.14  14.53  14.59  1333801.0  1.962605e+09
2020-08-21  14.71  14.71  14.32  14.45  1234517.0  1.787279e+09

[76 rows x 6 columns]

In [3]:
cn_stk_list = QA.QA_fetch_stock_list()
cn_stk_list.head(3)

          code  decimal_point  name    pre_close       sec sse  volunit
code
000001  000001              2  平安银行  1656.022500  stock_cn  sz      100
000002  000002              2  万 科Ａ    26.950001  stock_cn  sz      100
000004  000004              2  国农科技    23.450001  stock_cn  sz      100

In [4]:
cn_stk_list = cn_stk_list[~cn_stk_list['name'].str.contains('ST|退')]

In [5]:
cn_stk_list.head(3)

          code  decimal_point  name    pre_close       sec sse  volunit
code
000001  000001              2  平安银行  1656.022500  stock_cn  sz      100
000002  000002              2  万 科Ａ    26.950001  stock_cn  sz      100
000004  000004              2  国农科技    23.450001  stock_cn  sz      100

In [6]:
# 获取整个市场非st非退股票代码
cn_stk_code = cn_stk_list['code'].to_list()
cn_stk_code[:5]

['000001', '000002', '000004', '000005', '000006']

In [7]:
cn_stock_basic = ts.get_stock_basics()
cn_stock_basic.head()

,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,reserved,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
code,,,,,,,,,,,,,,,,,,,,,
688215,N瑞晟,专用机械,浙江,100.79,0.09,0.40,2.04,1.83,0.03,0.07,...,10.80,8.38,20200828,0.97,2.42,0.0,0.0,39.77,27.72,12390.0
688289,N圣湘,医疗保健,湖南,18.84,0.33,4.00,25.00,22.66,1.82,2.26,...,9.15,12.69,20200828,12.04,3.01,0.0,0.0,83.10,58.66,31650.0
688408,N中信博,电气设备,江苏,46.00,0.30,1.36,28.49,24.16,2.83,4.65,...,17.03,4.57,20200828,4.12,3.04,0.0,0.0,25.90,8.99,28426.0
688017,N绿的,机械基件,江苏,104.21,0.28,1.20,7.45,4.30,1.83,4.37,...,13.52,4.36,20200828,1.30,1.08,0.0,0.0,46.96,38.52,27759.0
002996,N顺博,铝,重庆,35.88,0.53,4.39,22.66,16.13,4.14,2.49,...,4.01,3.02,20200828,6.54,1.49,0.0,0.0,6.94,4.13,104660.0

In [8]:
#获取所有指数
idx_list = QA.QA_fetch_index_list_adv()
idx_list.head()
idx_list.to_csv('all block.csv',encoding='utf-8-sig')

In [9]:
#只获取板块/概念指数
idx_wanted = idx_list['880301':'880981'].name
# idx_wanted.to_csv('all_blk.csv',encoding='utf_8_sig')
#所有行业指数名
industry_name = idx_wanted['880301':'880497']
#所有概念指数名
concept_name = idx_wanted['880501':'880981']
idx_wanted.head(5)

code
880301      煤炭
880302    煤炭开采
880303    焦炭加工
880305      电力
880306    水力发电
Name: name, dtype: object

In [10]:
industry_name.head()

code
880301      煤炭
880302    煤炭开采
880303    焦炭加工
880305      电力
880306    水力发电
Name: name, dtype: object

In [44]:
idx_wanted_code = idx_list['880301':].code.to_list()
industry_code = idx_list['880301':'880497'].code.to_list()  #132
concept_code = idx_list['880501':'880981'].code.to_list() #362
industry_code[:4]

['880301', '880302', '880303', '880305']

In [15]:
tech_idx = ['880490','880491','880492','880493'] # 通讯，半导体，元器件，软件
consumer_idx = ['880381','880360','880390','880387'] #白酒，农林牧渔,汽车,家用电器

In [16]:
#获取所有板块5月到8月的数据
industry_data = QA.QA_fetch_index_day_adv(industry_code,'2020-08-01','2020-08-21')
concept_data = QA.QA_fetch_index_day_adv(concept_code,'2020-08-01','2020-08-21')

In [17]:
industry_code[1]

'880302'

In [18]:
#对个股进行标识，1：单涨停回调，2：变盘阳内回调...
def label_stock(data):
    pass

In [20]:
#找出行业/概念机会,返回列表
def label_blk_idx(data):
    pass
#找到行业板块机会
industry_opp = label_blk_idx(industry_data)
#找到概念板块机会
concept_opp = label_blk_idx(industry_data)

In [42]:
# industry_code
cnt = len(industry_code)
d_start = '2020-08-14'
d_end = '2020-08-14'
data = QA.QA_fetch_index_day_adv(industry_code[i],d_start,d_end)

In [43]:
#遍历所有板块，对所有板块进行label 
for i in range(cnt):
    data = QA.QA_fetch_index_day_adv(industry_code[i],d_start,d_end)
    industry_opp = label_blk_idx(data)

# industry_opp should contain 
# ma_ribbon 11+range,21+range,22+range  range is the how long period since 多头成立
# candle stick pattern

In [48]:
#传入板块名称,遍历板块个股
def find_opp_in_blk(opp_name):
    component = idx_wanted_code[opp_name]
    result = {}
    for code in component:
        data = QA.QA_fetch_stock_day_adv(code,d_start,d_end)
        label_stock(data) #遍历所有模型 eg 2yjs: [000001,000002,000003,etc]

In [49]:
result={}
result['000001'] = 'QS22'

In [51]:
result['000001'] = 'QS11'

In [52]:
result

{'000001': 'QS11'}

In [22]:
#从行业/概念机会选择个股机会
#获取板块个股
all_blk_component = QA.QA_fetch_stock_block_adv().view_block
all_blk_component.head(5)

blockname
300周期    [000001, 000002, 000069, 000166, 000627, 00065...
300非周    [000063, 000066, 000100, 000157, 000333, 00033...
3D打印     [000638, 000928, 000938, 000969, 000988, 00200...
4G5G     [300747, 002902, 300548, 000636, 603678, 30040...
5G概念     [000063, 000070, 000547, 000586, 000636, 00066...
dtype: object

In [23]:
# gold_component = all_blk_component['黄金概念']
target_component = all_blk_component[industry_name[industry_code[1]]]
industry_name[industry_code[1]]

'煤炭开采'

In [24]:
target_min=QA.QA_fetch_stock_min_adv(target_component,'2020-08-20','2020-08-21')
target_min.data.head(5)

                             open   high    low  close     volume  \
datetime            code
2020-08-20 09:31:00 000552   2.55   2.55   2.54   2.54   491300.0
                    000780   2.65   2.65   2.61   2.62    75400.0
                    000937   4.10   4.11   4.03   4.08  6282000.0
                    000983   4.37   4.39   4.36   4.38  1040300.0
                    002128  11.08  11.08  11.01  11.02   398800.0

                                  amount  type
datetime            code
2020-08-20 09:31:00 000552  1.248889e+06  1min
                    000780  1.981440e+05  1min
                    000937  2.568241e+07  1min
                    000983  4.547676e+06  1min
                    002128  4.409071e+06  1min

In [25]:
industry_min = QA.QA_fetch_index_min_adv(industry_code,'2020-08-21','2020-08-21')
len(industry_min)

31548

In [26]:
idx_name= idx_list['880301':'880981'].name 
idx_name.head()

code
880301      煤炭
880302    煤炭开采
880303    焦炭加工
880305      电力
880306    水力发电
Name: name, dtype: object

In [63]:
idx_name.loc['880301']

'煤炭'