知识点

fund_list_E.query('ts_code.str.contains("508018")',engine='python')

In [1]:
import tushare as ts
token = "488917d460bca13177c0b510492fc5fc04d0629bc76cc32a4f73fcf0"
ts.set_token(token)
pro = ts.pro_api()

# 基金列表

In [2]:
#  E场内
fund_list_E =  pro.fund_basic(market='E')

In [3]:
# O场外
fund_list_O =  pro.fund_basic(market='O')

In [88]:
fund_list_E.columns

Index(['ts_code', 'name', 'management', 'custodian', 'fund_type', 'found_date',
       'due_date', 'list_date', 'issue_date', 'delist_date', 'issue_amount',
       'm_fee', 'c_fee', 'duration_year', 'p_value', 'min_amount',
       'exp_return', 'benchmark', 'status', 'invest_type', 'type', 'trustee',
       'purc_startdate', 'redm_startdate', 'market'],
      dtype='object')

In [92]:
fund_list_E.query("name == '*半导体*'")

Empty DataFrame
Columns: [ts_code, name, management, custodian, fund_type, found_date, due_date, list_date, issue_date, delist_date, issue_amount, m_fee, c_fee, duration_year, p_value, min_amount, exp_return, benchmark, status, invest_type, type, trustee, purc_startdate, redm_startdate, market]
Index: []

[0 rows x 25 columns]

In [4]:
fund_list_E

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
0,508066.SH,华泰江苏交控REIT,华泰证券资管,中国建设银行,REITs,20221103,None,None,20221028,None,...,0.1,None,None,I,None,契约型封闭式,None,None,None,E
1,588350.SH,双创50ETF基金,鹏扬基金,中国农业银行,股票型,20221026,None,20221110,20221011,None,...,0.1,None,中证科创创业50指数收益率,I,被动指数型,契约型开放式,None,20221110,20221110,E
2,159630.SZ,中证100ETF基金,汇添富基金,中国工商银行,股票型,20221020,None,20221101,20220910,None,...,0.1,None,中证100指数收益率,L,被动指数型,契约型开放式,None,20221101,20221101,E
3,561330.SH,矿业ETF,国泰基金,海通证券,股票型,20221019,None,20221101,20220921,None,...,0.1,None,中证有色金属矿业主题指数收益率,L,被动指数型,契约型开放式,None,20221101,20221101,E
4,560680.SH,消费ETF龙头,广发基金,华泰证券,股票型,20221019,None,20221031,20220919,None,...,0.1,None,中证主要消费指数,L,被动指数型,契约型开放式,None,20221031,20221031,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,500017.SH,基金景业,大成基金,中国农业银行,股票型,19920401,20070115,20011219,None,20070116,...,NaN,None,None,D,成长型,契约型封闭式,None,20011219,None,E
1714,184702.SZ,基金同智,长盛基金,中国银行,股票型,19920313,20070104,20000515,None,20070105,...,NaN,None,None,D,成长型,契约型封闭式,None,20000515,None,E
1715,500028.SH,基金兴业,华夏基金,中国农业银行,股票型,19911115,20060808,20010727,None,20060809,...,NaN,None,None,D,平衡型,契约型封闭式,None,20010727,None,E
1716,508009.SH,中金安徽交控REIT,中金基金,招商银行,REITs,None,None,None,20221107,None,...,0.1,None,None,I,None,契约型封闭式,None,None,None,E
1717,508077.SH,华夏基金华润有巢REIT,华夏基金,浦发银行,REITs,None,None,None,20221114,None,...,NaN,None,None,I,None,契约型封闭式,None,None,None,E

In [5]:
fund_list_O

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
0,016204.OF,东方沪深300指数增强A,东方基金,中国工商银行,股票型,20221108,None,None,20221017,None,...,0.0001,None,沪深300指数收益率*95%+银行活期存款利率(税后)*5%,L,增强指数型,契约型开放式,None,None,None,O
1,015262.OF,易方达如意兴安一年持有C,易方达基金,兴业银行,混合型,20221108,None,None,20220805,None,...,0.0001,None,中债新综合指数(财富)收益率*80%+沪深300指数收益率*18%+中证港股通综合指数收益率*2%,L,混合型,契约型开放式,None,None,None,O
2,015235.OF,国寿安保稳泽两年持有A,国寿安保基金,中国民生银行,混合型,20221108,None,None,20220805,None,...,0.0010,None,中债综合(全价)指数收益率*80%+沪深300指数收益率*15%+恒生指数收益率*5%,L,混合型,契约型开放式,None,None,None,O
3,016205.OF,东方沪深300指数增强C,东方基金,中国工商银行,股票型,20221108,None,None,20221017,None,...,0.0001,None,沪深300指数收益率*95%+银行活期存款利率(税后)*5%,L,增强指数型,契约型开放式,None,None,None,O
4,016424.OF,广发集汇A,广发基金,中国银行,债券型,20221108,None,None,20221017,None,...,0.0001,None,中债总全价(总值)指数收益率*90%+沪深300指数收益率*5%+人民币计价的恒生指数收益率*5%,L,债券型,契约型开放式,None,None,None,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,001676.OF,江信同福C,江信基金,中国光大银行,混合型,20150828,None,None,20150810,None,...,0.1000,None,沪深300指数*50%+上证国债指数*50%,L,灵活配置型,契约型开放式,None,20151117,20151117,O
14996,001675.OF,江信同福A,江信基金,中国光大银行,混合型,20150828,None,None,20150810,None,...,0.1000,None,沪深300指数*50%+上证国债指数*50%,L,灵活配置型,契约型开放式,None,20151117,20151117,O
14997,001730.OF,兴银大健康,兴银基金,兴业银行,混合型,20150827,None,None,20150810,None,...,0.0100,None,中证健康产业指数收益率*80%+中证综合债指数收益率*20%,L,灵活配置型,契约型开放式,None,20151102,20151102,O
14998,001728.OF,银华战略新兴,银华基金,中国建设银行,混合型,20150827,None,None,20150803,None,...,0.1000,None,年化收益率6%,L,灵活配置型,契约型开放式,None,20151124,20151124,O
14999,1602251.OF,国泰国证新能源汽车分级,国泰基金,中国银行,股票型,20150827,20160630,None,20150827,None,...,NaN,None,国证新能源汽车指数收益率*95%+银行活期存款利率(税后)*5%,D,被动指数型,契约型开放式,None,20151023,20151023,O

In [6]:
# 场内基金的类型
fund_list_E.fund_type.unique()

array(['REITs', '股票型', '债券型', '混合型', '商品型', '货币市场型', '另类投资型'],
      dtype=object)

In [7]:
# 基金的类型
fund_list_O.fund_type.unique()

array(['股票型', '混合型', '债券型', '货币市场型', '商品型', '保本型', '另类投资型'], dtype=object)

In [8]:
fund_list_O.columns

Index(['ts_code', 'name', 'management', 'custodian', 'fund_type', 'found_date',
       'due_date', 'list_date', 'issue_date', 'delist_date', 'issue_amount',
       'm_fee', 'c_fee', 'duration_year', 'p_value', 'min_amount',
       'exp_return', 'benchmark', 'status', 'invest_type', 'type', 'trustee',
       'purc_startdate', 'redm_startdate', 'market'],
      dtype='object')

In [10]:
import numpy as np

In [11]:
np.nan == np.nan

False

In [12]:
fund_list_E.filter(['ts_code','fund_type','found_date','list_date','delist_date','m_fee','c_fee','benchmark','invest_type','purc_startdate'])
# .query("benchmark == benchmark")
# .query("delist_date != delist_date")
# status 存续状态D摘牌 I发行 L已上市

,ts_code,fund_type,found_date,list_date,delist_date,m_fee,c_fee,benchmark,invest_type,purc_startdate
0,508066.SH,REITs,20221103,None,None,0.30,0.01,None,None,None
1,588350.SH,股票型,20221026,20221110,None,0.50,0.10,中证科创创业50指数收益率,被动指数型,20221110
2,159630.SZ,股票型,20221020,20221101,None,0.15,0.05,中证100指数收益率,被动指数型,20221101
3,561330.SH,股票型,20221019,20221101,None,0.50,0.10,中证有色金属矿业主题指数收益率,被动指数型,20221101
4,560680.SH,股票型,20221019,20221031,None,0.50,0.10,中证主要消费指数,被动指数型,20221031
...,...,...,...,...,...,...,...,...,...,...
1713,500017.SH,股票型,19920401,20011219,20070116,1.50,0.25,None,成长型,20011219
1714,184702.SZ,股票型,19920313,20000515,20070105,1.50,0.25,None,成长型,20000515
1715,500028.SH,股票型,19911115,20010727,20060809,1.50,0.25,None,平衡型,20010727
1716,508009.SH,REITs,None,None,None,0.09,0.01,None,None,None
1717,508077.SH,REITs,None,None,None,0.10,0.01,None,None,None

# 查询基金代码

In [13]:
fund_list_E.query('ts_code.str.contains("508018")',engine='python')
# 159638.SZ
# 159638

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
85,508018.SH,华夏中国交建REIT,华夏基金,中国农业银行,REITs,20220413,None,20220428,20220407,None,...,NaN,None,None,L,None,契约型封闭式,None,None,None,E

In [15]:
fund_list_E.query("ts_code=='159638.SZ'")

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
33,159638.SZ,高端装备ETF,嘉实基金,兴业银行,股票型,20220805,None,20220812,20220718,None,...,0.1,None,中证高端装备细分50指数收益率,L,被动指数型,契约型开放式,None,20220812,20220812,E

# 基金规模

In [129]:
# pro.fund_share(ts_code='150018.SZ')
pro.fund_share(ts_code='510300.SH')

        ts_code trade_date    fd_share fund_type market
0     510300.SH   20221118  1643268.77       ETF     SH
1     510300.SH   20221117  1649568.77       ETF     SH
2     510300.SH   20221116  1645428.77       ETF     SH
3     510300.SH   20221115  1642098.77       ETF     SH
4     510300.SH   20221114  1624818.77       ETF     SH
...         ...        ...         ...       ...    ...
1995  510300.SH   20140912   721700.00       ETF     SH
1996  510300.SH   20140911   723600.00       ETF     SH
1997  510300.SH   20140910   723700.00       ETF     SH
1998  510300.SH   20140909   723100.00       ETF     SH
1999  510300.SH   20140905   718700.00       ETF     SH

[2000 rows x 5 columns]

# 基金净值

In [130]:
pro.fund_nav(ts_code='510300.SH')

,ts_code,ann_date,nav_date,unit_nav,accum_nav,accum_div,net_asset,total_netasset,adj_nav,update_flag
0,510300.SH,20221119,20221118,3.8628,1.6317,None,NaN,NaN,1.667720,0
1,510300.SH,20221118,20221117,3.8795,1.6379,None,NaN,NaN,1.674930,0
2,510300.SH,20221117,20221116,3.8961,1.6441,None,NaN,NaN,1.682097,0
3,510300.SH,20221116,20221115,3.9279,1.6559,None,NaN,NaN,1.695826,0
4,510300.SH,20221115,20221114,3.8567,1.6295,None,NaN,NaN,1.665087,0
...,...,...,...,...,...,...,...,...,...,...
2574,510300.SH,20120526,20120525,2.5740,0.9550,None,3.147690e+10,3.147690e+10,0.954800,0
2575,510300.SH,20120523,20120521,2.5880,0.9600,None,3.164767e+10,3.164767e+10,0.960000,0
2576,510300.SH,20120519,20120518,2.5740,0.9550,None,3.148189e+10,3.148189e+10,0.954800,0
2577,510300.SH,20120512,20120511,2.6370,0.9780,None,3.224872e+10,3.224872e+10,0.978200,0
2578,510300.SH,20120505,20120504,1.0000,1.0000,None,3.296863e+10,3.296863e+10,1.000000,0

# 股票列表

In [24]:
stock_basics = pro.stock_basic(exchange='SSE', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')

In [59]:
stock_code_name = stock_basics.filter(['symbol','name'])

# 基金持仓

In [41]:
## 军工ETF
df = pro.fund_portfolio(ts_code='512660.SH') #半导体ETF
df.query('end_date == "20220630"').sort_values(by='stk_mkv_ratio',ascending = 0)
# df

,ts_code,ann_date,end_date,symbol,mkv,amount,stk_mkv_ratio,stk_float_ratio
9,512660.SH,20220721,20220630,600893.SH,6.885413e+08,15129450.0,5.82,0.65
2,512660.SH,20220721,20220630,002179.SZ,5.755675e+08,9089822.0,4.86,0.60
0,512660.SH,20220721,20220630,000733.SZ,5.485125e+08,4034070.0,4.63,0.78
7,512660.SH,20220721,20220630,600760.SH,5.486881e+08,9076727.0,4.63,0.46
1,512660.SH,20220721,20220630,000768.SZ,4.888159e+08,16137863.0,4.13,0.58
...,...,...,...,...,...,...,...,...
69,512660.SH,20220830,20220630,301222.SZ,9.614720e+03,332.0,0.00,0.00
70,512660.SH,20220830,20220630,301238.SZ,1.121488e+05,3497.0,0.00,0.00
71,512660.SH,20220830,20220630,301239.SZ,1.933865e+05,5747.0,0.00,0.02
72,512660.SH,20220830,20220630,301263.SZ,2.140116e+04,682.0,0.00,0.00
102,512660.SH,20220830,20220630,688290.SH,1.424848e+05,3040.0,0.00,0.02

## 定义函数

In [82]:
def get_latest_holding(code,dt,stock_code_name):
    df = pro.fund_portfolio(ts_code=code) 
    df['code'] = df['symbol'].map(lambda x: x.replace('.SH','').replace('.SZ','').replace('.BJ',''))
    latest_data = df.query('end_date == @dt').sort_values(by='stk_mkv_ratio',ascending = 0)
    latest_holding = latest_data.merge(stock_code_name,how='inner',left_on='code',right_on='symbol')
    return latest_holding.filter(['ts_code','code','mkv','amount','stk_mkv_ratio','name'])

In [ ]:
fund_list_E[fund_list_E.name.str.contains('半')]

## 房地产ETF

In [84]:
get_latest_holding('159768.SZ','20220930',stock_code_name)

     ts_code    code          mkv     amount  stk_mkv_ratio    name
0  159768.SZ  600048  30996000.00  1722000.0          17.90    保利发展
1  159768.SZ  600383  13455939.00  1171100.0           7.77    金地集团
2  159768.SZ  600325   7189515.00   729900.0           4.15    华发股份
3  159768.SZ  601155   6848664.00   391800.0           3.95    新城控股
4  159768.SZ  600606   5077297.80  1819820.0           2.93    绿地控股
5  159768.SZ  600848   4845018.00   409900.0           2.80    上海临港
6  159768.SZ  688387    104932.26    21591.0           0.06  信科移动-U
7  159768.SZ  688459     78125.74     5753.0           0.05    哈铁科技
8  159768.SZ  688073     89584.00     1018.0           0.05    毕得医药
9  159768.SZ  688252     47296.08     2934.0           0.03     天德钰

In [85]:
get_latest_holding('512200.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio    name
0  512200.SH  600048  4.973847e+08  27632485.0          12.43    保利发展
1  512200.SH  600383  1.959661e+08  17055363.0           4.90    金地集团
2  512200.SH  600325  1.047824e+08  10637812.0           2.62    华发股份
3  512200.SH  601155  9.957704e+07   5696627.0           2.49    新城控股
4  512200.SH  600606  7.399776e+07  26522495.0           1.85    绿地控股
5  512200.SH  600848  7.103196e+07   6009472.0           1.77    上海临港
6  512200.SH  688072  1.545268e+06      5300.0           0.04  拓荆科技-U
7  512200.SH  688409  4.433167e+05      6334.0           0.01    富创精密

## 信息产业

### 半导体ETF

In [96]:
fund_list_E[fund_list_E.name.str.contains('半')]

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
524,159813.SZ,半导体ETF,鹏华基金,申万宏源证券,股票型,20200417,None,20200525,20200325,None,...,0.1,None,国证半导体芯片指数收益率,L,被动指数型,契约型开放式,None,20200525,20200525,E
685,512480.SH,半导体ETF,国联安基金,国泰君安,股票型,20190508,None,20190612,20190422,None,...,0.1,None,中证全指半导体产品与设备指数收益率,L,被动指数型,契约型开放式,None,20190612,20190612,E

In [97]:
get_latest_holding('159813.SZ','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio  name
0  159813.SZ  688981  1.201744e+08  3180900.0           6.93  中芯国际
1  159813.SZ  603501  1.070631e+08  1336117.0           6.17  韦尔股份
2  159813.SZ  603986  9.663891e+07  1030815.0           5.57  兆易创新
3  159813.SZ  600703  7.670771e+07  4388313.0           4.42  三安光电
4  159813.SZ  688012  6.680389e+07   619300.0           3.85  中微公司
5  159813.SZ  600745  6.057065e+07  1270624.0           3.49  闻泰科技
6  159813.SZ  688409  4.433167e+05     6334.0           0.03  富创精密
7  159813.SZ  688392  2.872917e+05     2745.0           0.02  骄成超声

In [87]:
get_latest_holding('512480.SH','20220930',stock_code_name)

      ts_code    code           mkv      amount  stk_mkv_ratio    name
0   512480.SH  688981  8.616460e+08  22806936.0           7.14    中芯国际
1   512480.SH  603986  7.374233e+08   7865849.0           6.11    兆易创新
2   512480.SH  603501  6.685489e+08   8343304.0           5.54    韦尔股份
3   512480.SH  688012  4.697627e+08   4354897.0           3.89    中微公司
4   512480.SH  600584  3.591398e+08  16758741.0           2.97    长电科技
5   512480.SH  600460  3.209845e+08  10015118.0           2.66     士兰微
6   512480.SH  688348  3.233448e+06      5644.0           0.03    昱能科技
7   512480.SH  600938  1.295342e+06     84004.0           0.01    中国海油
8   512480.SH  688072  1.545268e+06      5300.0           0.01  拓荆科技-U
9   512480.SH  688153  2.627578e+05      7674.0           0.00  唯捷创芯-U
10  512480.SH  688409  4.433167e+05      6334.0           0.00    富创精密

### 芯片ETF

In [104]:
fund_list_E.query('name.str.contains("芯")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
8,588290.SH,科创板芯片ETF,华安基金,华泰证券,股票型,20220930,None,20221026,20220923,None,...,0.1,None,上证科创板芯片指数收益率,L,被动指数型,契约型开放式,None,20221026,20221026,E
11,588200.SH,科创芯片ETF,嘉实基金,中信证券,股票型,20220930,None,20221026,20220923,None,...,0.1,None,上证科创板芯片指数收益率,L,被动指数型,契约型开放式,None,20221026,20221026,E
151,516350.SH,芯片50ETF,易方达基金,中国银行,股票型,20211215,None,20211223,20210930,None,...,0.1,None,中证芯片产业指数收益率,L,被动指数型,契约型开放式,None,20211223,20211223,E
238,516640.SH,芯片龙头ETF,富国基金,兴业银行,股票型,20210819,None,20210827,20210802,None,...,0.1,None,中证芯片产业指数收益率,L,被动指数型,契约型开放式,None,20210827,20210827,E
260,516920.SH,芯片ETF基金,汇添富基金,招商银行,股票型,20210727,None,20210816,20210708,None,...,0.1,None,中证芯片产业指数收益率,L,被动指数型,契约型开放式,None,20210816,20210816,E
569,159995.SZ,芯片ETF,华夏基金,中国建设银行,股票型,20200120,None,20200210,20191224,None,...,0.1,None,国证半导体芯片指数收益率,L,被动指数型,契约型开放式,None,20200210,20200210,E
572,159801.SZ,芯片龙头ETF,广发基金,中国工商银行,股票型,20200120,None,20200218,20200106,None,...,0.1,None,国证半导体芯片指数收益率,L,被动指数型,契约型开放式,None,20200218,20200218,E
683,512760.SH,芯片ETF,国泰基金,中国银行,股票型,20190516,None,20190612,20190422,None,...,0.1,None,中华交易服务半导体芯片行业指数收益率,L,被动指数型,契约型开放式,None,20190612,20190612,E

In [119]:
# fund_list_E[fund_list_E.name.str.contains('芯')]

In [116]:
# get_latest_holding('516350.SH','20220930',stock_code_name) # To small

In [115]:
# get_latest_holding('516640.SH','20220930',stock_code_name)  # to small

In [114]:
# get_latest_holding('512760.SH','20220930',stock_code_name) # too small

In [152]:
get_latest_holding('512760.SH','20220930',stock_code_name)

      ts_code    code           mkv      amount  stk_mkv_ratio    name
0   512760.SH  688981  7.511432e+08  19882032.0           6.69    中芯国际
1   512760.SH  603986  6.212117e+08   6626258.0           5.53    兆易创新
2   512760.SH  603501  5.860234e+08   7313408.0           5.22    韦尔股份
3   512760.SH  600703  4.846872e+08  27728103.0           4.32    三安光电
4   512760.SH  688012  3.895013e+08   3610840.0           3.47    中微公司
5   512760.SH  600745  3.733625e+08   7832232.0           3.33    闻泰科技
6   512760.SH  688271  1.177222e+06      7365.0           0.01    联影医疗
7   512760.SH  688428  6.094340e+05     70700.0           0.01  诺诚健华-U
8   512760.SH  688073  2.238720e+05      2544.0           0.00    毕得医药
9   512760.SH  688119  1.969626e+05     33327.0           0.00    中钢洛耐
10  512760.SH  688409  4.433167e+05      6334.0           0.00    富创精密

In [112]:
get_latest_holding('516920.SH','20220930',stock_code_name)

     ts_code    code          mkv    amount  stk_mkv_ratio    name
0  516920.SH  688981  23302704.00  616800.0           6.97    中芯国际
1  516920.SH  603986  20175000.00  215200.0           6.03    兆易创新
2  516920.SH  603501  18445124.70  230190.0           5.52    韦尔股份
3  516920.SH  600703  14793324.00  846300.0           4.42    三安光电
4  516920.SH  688012  12664693.09  117407.0           3.79    中微公司
5  516920.SH  600745  11350227.00  238100.0           3.40    闻泰科技
6  516920.SH  688072    278148.24     954.0           0.08  拓荆科技-U
7  516920.SH  688409    118213.11    1689.0           0.04    富创精密
8  516920.SH  688302     90872.82    2907.0           0.03  海创药业-U

In [117]:
get_latest_holding('159995.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  159995.SZ  688981  1.232893e+09  32633490.0           6.93  中芯国际
1  159995.SZ  603501  1.098266e+09  13706054.0           6.18  韦尔股份
2  159995.SZ  603986  9.910451e+08  10571148.0           5.57  兆易创新
3  159995.SZ  600703  7.868148e+08  45012287.0           4.42  三安光电
4  159995.SZ  688012  6.849499e+08   6349772.0           3.85  中微公司
5  159995.SZ  600745  6.212982e+08  13033317.0           3.49  闻泰科技

### 5G

In [180]:
get_latest_holding('515050.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  515050.SH  603986  4.627355e+08   4935845.0           5.81  兆易创新
1  515050.SH  600703  3.475689e+08  19883805.0           4.36  三安光电
2  515050.SH  600745  2.636476e+08   5530682.0           3.31  闻泰科技

## 稀土

In [154]:
get_latest_holding('516150.SH','20220930',stock_code_name)

      ts_code    code           mkv      amount  stk_mkv_ratio  name
0   516150.SH  600111  2.340143e+08   8810781.0          11.77  北方稀土
1   516150.SH  600549  1.167504e+08   5159100.0           5.87  厦门钨业
2   516150.SH  600392  9.804920e+07   6476169.0           4.93  盛和资源
3   516150.SH  600010  9.600752e+07  52178000.0           4.83  包钢股份
4   516150.SH  601600  8.973458e+07  21727500.0           4.52  中国铝业
5   516150.SH  600416  8.355192e+07   4200700.0           4.20  湘电股份
6   516150.SH  688349  1.119568e+06     32650.0           0.06  三一重能
7   516150.SH  688331  8.385613e+05     15915.0           0.04  荣昌生物
8   516150.SH  688409  4.433167e+05      6334.0           0.02  富创精密
9   516150.SH  688380  2.799082e+05     12677.0           0.01  中微半导
10  516150.SH  688459  2.343772e+05     17259.0           0.01  哈铁科技

## 证券ETF

In [153]:
fund_list_E.query('name.str.contains("证券")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
192,516730.SH,证券公司ETF,浦银安盛基金,招商银行,股票型,20211104,None,20211112,20210930,None,...,0.100,None,中证证券公司30指数收益率,L,被动指数型,契约型开放式,None,20211112,20211112,E
310,516980.SH,证券ETF先锋,华富基金,中国银行,股票型,20210615,None,20210624,20210309,None,...,0.100,None,中证证券公司先锋策略指数收益率,L,被动指数型,契约型开放式,None,20210624,20210624,E
382,516200.SH,证券行业ETF,华安基金,中国建设银行,股票型,20210309,None,20210322,20210222,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20210322,20210322,E
402,159848.SZ,证券ETF基金,国联安基金,国泰君安,股票型,20210209,None,20210312,20210128,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20210312,20210312,E
421,159841.SZ,证券ETF,天弘基金,国泰君安,股票型,20210128,None,20210209,20210118,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20210209,20210209,E
503,515560.SH,证券ETF建信,建信基金,中信证券,股票型,20200629,None,20200720,20200428,None,...,0.100,None,中证全指证券公司指数,L,被动指数型,契约型开放式,None,20200720,20200720,E
517,515190.SH,中银证券500ETF,中银证券,招商银行,股票型,20200430,None,20200527,20200330,None,...,0.100,None,中证500指数收益率,L,被动指数型,契约型开放式,None,20200527,20200527,E
531,510200.SH,上证券商ETF,汇安基金,兴业证券,股票型,20200409,None,20200508,20200316,None,...,0.100,None,上证证券行业指数,L,被动指数型,契约型开放式,None,20200508,20200508,E
549,513090.SH,香港证券ETF,易方达基金,招商银行,股票型,20200313,None,20200326,20200224,None,...,0.100,None,中证香港证券投资主题指数收益率(使用估值汇率折算),L,被动指数型,契约型开放式,None,20200326,20200326,E
550,501095.SH,中银证券科技创新,中银证券,中国农业银行,混合型,20200312,None,20200708,20200227,None,...,0.001,None,中国战略新兴产业成份指数收益率*55%+中债综合全价指数收益率*45%,L,灵活配置型,契约型开放式,None,None,None,E
557,515630.SH,保险证券ETF,鹏华基金,中国建设银行,股票型,20200228,None,20200403,20200113,None,...,0.100,None,中证800证券保险指数收益率,L,被动指数型,契约型开放式,None,20200403,20200403,E
568,515850.SH,证券龙头ETF,富国基金,中国建设银行,股票型,20200121,None,20200221,20191016,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20200221,20200221,E
669,513800.SH,东京证券指数ETF,南方基金,中国工商银行,股票型,20190612,None,20190625,20190528,None,...,0.100,None,"东证指数(Tokyo Stock Price Index,“TOPIX”)(经汇率调整后)",L,被动指数型,契约型开放式,None,20190625,20190625,E
777,501048.SH,证券公司LOFC,汇添富基金,中信建投证券,股票型,20171204,None,20180118,20171108,None,...,0.001,None,中证全指证券公司指数收益率*95%+银行人民币活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20180118,20180118,E
778,501047.SH,证券公司LOF,汇添富基金,中信建投证券,股票型,20171204,None,20180118,20171108,None,...,0.001,None,中证全指证券公司指数收益率*95%+银行人民币活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20180118,20180118,E
807,512570.SH,证券ETF易方达,易方达基金,招商银行,股票型,20170727,None,20170811,20170615,None,...,0.100,None,中证全指证券公司指数,L,被动指数型,契约型开放式,None,20170811,20170811,E
842,512900.SH,证券ETF基金,南方基金,中国银行,股票型,20170310,None,20170331,20170126,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20170331,20170331,E
917,512880.SH,证券ETF,国泰基金,中国建设银行,股票型,20160726,None,20160808,20160620,None,...,0.100,None,中证全指证券公司指数收益率,L,被动指数型,契约型开放式,None,20160808,20160808,E
995,150343.SZ,证券A基,融通基金,中国建设银行,股票型,20150717,20201119,20150803,20150708,20201119,...,0.001,None,中证全指证券公司价格指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150803,None,E
996,150344.SZ,证券B基,融通基金,中国建设银行,股票型,20150717,20201119,20150803,20150708,20201119,...,0.001,None,中证全指证券公司价格指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150803,None,E
1003,502010.SH,证券LOF,易方达基金,中国建设银行,股票型,20150708,None,20150715,20150623,None,...,0.010,None,中证全指证券公司指数收益率*95%+同期银行活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20150715,20150715,E
1004,502011.SH,证券A,易方达基金,中国建设银行,股票型,20150708,20201231,20150715,20150623,20210105,...,0.010,None,中证全指证券公司指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150715,None,E
1006,502012.SH,证券B,易方达基金,中国建设银行,股票型,20150708,20201231,20150715,20150623,20210105,...,0.010,None,中证全指证券公司指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150715,None,E
1068,150302.SZ,证券股B,华安基金,中国建设银行,股票型,20150609,20201231,20150618,20150528,20210104,...,0.010,None,中证全指证券公司指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1069,150301.SZ,证券股A,华安基金,中国建设银行,股票型,20150609,20201231,20150618,20150528,20210104,...,0.010,None,中证全指证券公司指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1175,150223.SZ,证券A级,富国基金,中国建设银行,股票型,20150327,20201231,20150410,20150316,20210104,...,0.010,None,中证全指证券公司指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150410,None,E
1176,161027.SZ,证券LOF,富国基金,中国建设银行,股票型,20150327,None,20210118,20150316,None,...,0.010,None,中证全指证券公司指数收益率*95%+银行人民币活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20150410,20150410,E
1177,150224.SZ,证券B级,富国基金,中国建设银行,股票型,20150327,20201231,20150410,20150316,20210104,...,0.010,None,中证全指证券公司指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150410,None,E
1219,161720.SZ,证券基金LOF,招商基金,中国银行,股票型,20141113,None,20210122,20141020,None,...,0.100,None,中证全指证券公司指数收益率*95%+金融机构人民币活期存款基准利率(税后)*5%,L,被动指数型,契约型开放式,None,20141128,20141128,E
1253,512070.SH,证券保险ETF,易方达基金,中国建设银行,股票型,20140626,None,20140718,20140609,None,...,0.100,None,沪深300非银行金融指数,L,被动指数型,契约型开放式,None,20140718,20140718,E
1281,163113.SZ,申万证券LOF,申万菱信基金,中国工商银行,股票型,20140313,None,20210125,20140224,None,...,0.100,None,中证申万证券行业指数收益率*95%+银行同业存款利率*5%,L,被动指数型,契约型开放式,None,20140331,20140331,E
1282,150171.SZ,证券A,申万菱信基金,中国工商银行,股票型,20140313,20201231,20140331,20140224,20210104,...,0.100,None,中证申万证券行业指数收益率*95%+银行同业存款利率*5%,D,被动指数型,契约型封闭式,None,20140331,None,E
1283,150172.SZ,证券B,申万菱信基金,中国工商银行,股票型,20140313,20201231,20140331,20140224,20210104,...,0.100,None,中证申万证券行业指数收益率*95%+银行同业存款利率*5%,D,被动指数型,契约型封闭式,None,20140331,None,E

In [121]:
get_latest_holding('512880.SH','20220930',stock_code_name)

      ts_code    code           mkv       amount  stk_mkv_ratio    name
0   512880.SH  600030  3.757743e+09  215714321.0          13.00    中信证券
1   512880.SH  600837  1.845836e+09  213145012.0           6.38    海通证券
2   512880.SH  601688  1.583634e+09  130662873.0           5.48    华泰证券
3   512880.SH  601211  1.353231e+09   98992737.0           4.68    国泰君安
4   512880.SH  600999  1.003381e+09   81311252.0           3.47    招商证券
5   512880.SH  600958  8.966167e+08  116595147.0           3.10    东方证券
6   512880.SH  601377  8.519955e+08  156329445.0           2.95    兴业证券
7   512880.SH  688045  1.837150e+05       3939.0           0.00     必易微
8   512880.SH  688073  2.238720e+05       2544.0           0.00    毕得医药
9   512880.SH  688293  2.657968e+05       2452.0           0.00     奥浦迈
10  512880.SH  688351  1.379196e+05      10946.0           0.00  微电生理-U
11  512880.SH  688409  4.433167e+05       6334.0           0.00    富创精密

In [122]:
get_latest_holding('512000.SH','20220930',stock_code_name)

      ts_code    code           mkv       amount  stk_mkv_ratio  name
0   512000.SH  600030  2.803624e+09  160942833.0          13.00  中信证券
1   512000.SH  600837  1.378169e+09  159141932.0           6.39  海通证券
2   512000.SH  601688  1.176468e+09   97068348.0           5.45  华泰证券
3   512000.SH  601211  1.016046e+09   74326728.0           4.71  国泰君安
4   512000.SH  600999  7.552497e+08   61203379.0           3.50  招商证券
5   512000.SH  600958  6.626584e+08   86171444.0           3.07  东方证券
6   512000.SH  601377  6.259447e+08  114852243.0           2.90  兴业证券
7   512000.SH  688041  3.593245e+06      70208.0           0.02  海光信息
8   512000.SH  688035  3.392061e+05       4981.0           0.00  德邦科技
9   512000.SH  688073  2.238720e+05       2544.0           0.00  毕得医药
10  512000.SH  688125  1.964744e+05       3774.0           0.00  安达智能
11  512000.SH  688459  2.343772e+05      17259.0           0.00  哈铁科技

In [123]:
get_latest_holding('512900.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512900.SH  600030  1.023045e+09  58728158.0          13.00  中信证券
1  512900.SH  600837  5.034249e+08  58132205.0           6.39  海通证券
2  512900.SH  601688  4.291107e+08  35405177.0           5.45  华泰证券
3  512900.SH  601211  3.711077e+08  27147598.0           4.71  国泰君安
4  512900.SH  600999  2.764497e+08  22402727.0           3.51  招商证券
5  512900.SH  600958  2.418647e+08  31451841.0           3.07  东方证券
6  512900.SH  601377  2.287869e+08  41979240.0           2.91  兴业证券
7  512900.SH  688120  1.515121e+06      4822.0           0.02  华海清科
8  512900.SH  688409  4.433167e+05      6334.0           0.01  富创精密

In [18]:
df.query("end_date=='20220630'").groupby(['ts_code'])['stk_mkv_ratio'].sum()

Series([], Name: stk_mkv_ratio, dtype: float64)

## 银行

In [124]:
fund_list_E.query('name.str.contains("银行")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
94,517900.SH,银行ETF优选,招商基金,交通银行,股票型,20220315,None,20220325,20211210,None,...,0.10,None,中证银行AH价格优选指数(人民币)收益率,L,被动指数型,契约型开放式,None,20220325,20220325,E
228,516210.SH,银行股ETF,华安基金,中国银行,股票型,20210903,None,20210924,20210802,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20210924,20210924,E
339,516310.SH,银行ETF易方达,易方达基金,中国建设银行,股票型,20210520,None,20210528,20210430,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20210528,20210528,E
347,159887.SZ,银行ETF,富国基金,招商银行,股票型,20210512,None,20210520,20210412,None,...,0.10,None,中证800银行指数收益率,L,被动指数型,契约型开放式,None,20210520,20210520,E
440,515290.SH,银行ETF天弘,天弘基金,招商证券,股票型,20201211,None,20201228,20201207,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20201228,20201228,E
474,161121.SZ,银行LOF易方达,易方达基金,中国建设银行,股票型,20200807,None,20200818,20200807,None,...,NaN,None,中证银行指数收益率*95%+活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20200807,20200807,E
534,515280.SH,银行龙头ETF,富国基金,中信证券,股票型,20200401,None,20200417,20200311,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20200417,20200417,E
584,512730.SH,中证银行ETF,鹏华基金,中国建设银行,股票型,20191219,None,20200207,20191008,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20200207,20200207,E
615,515020.SH,银行ETF华夏,华夏基金,中国银行,股票型,20191024,None,20191203,20190909,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20191203,20191203,E
684,161029.SZ,银行龙头LOF,富国基金,中国农业银行,股票型,20190510,None,20190617,20190510,None,...,NaN,None,中证银行指数收益率*95%+银行人民币活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20190513,20190513,E
724,512820.SH,银行业ETF,汇添富基金,招商银行,股票型,20181023,None,20181123,20180717,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20181123,20181123,E
810,512800.SH,银行ETF,华宝基金,中国银行,股票型,20170718,None,20170803,20170525,None,...,0.10,None,中证银行指数,L,被动指数型,契约型开放式,None,20170803,20170803,E
816,512700.SH,银行ETF基金,南方基金,中国工商银行,股票型,20170628,None,20170726,20170524,None,...,0.10,None,中证银行指数收益率,L,被动指数型,契约型开放式,None,20170726,20170726,E
882,501025.SH,香港银行LOF,鹏华基金,中国建设银行,股票型,20161110,None,20161124,20161010,None,...,0.10,None,中证香港银行投资指数收益率*95%+银行活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20161124,20161124,E
1065,150267.SZ,银行A类,博时基金,中国建设银行,股票型,20150609,20200805,20150618,20150525,20200804,...,0.01,None,中证银行指数收益率*95%+金融机构人民币活期存款基准利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1066,150268.SZ,银行B类,博时基金,中国建设银行,股票型,20150609,20200805,20150618,20150525,20200804,...,0.01,None,中证银行指数收益率*95%+金融机构人民币活期存款基准利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1072,150299.SZ,银行股A,华安基金,中国银行,股票型,20150609,20201231,20150618,20150528,20210104,...,0.01,None,中证银行指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1073,150300.SZ,银行股B,华安基金,中国银行,股票型,20150609,20201231,20150618,20150528,20210104,...,0.01,None,中证银行指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150618,None,E
1075,150292.SZ,银行B份,中融基金,海通证券,股票型,20150605,20201013,20150615,20150601,20201013,...,0.10,None,中证银行指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150615,None,E
1076,150291.SZ,银行A份,中融基金,海通证券,股票型,20150605,20201013,20150615,20150601,20201013,...,0.10,None,中证银行指数收益率*95%+同期银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150615,None,E
1086,150255.SZ,银行业A,易方达基金,中国建设银行,股票型,20150603,20200806,20150611,20150518,20200805,...,0.01,None,中证银行指数收益率*95%+活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150611,None,E
1087,150256.SZ,银行业B,易方达基金,中国建设银行,股票型,20150603,20200806,20150611,20150518,20200805,...,0.01,None,中证银行指数收益率*95%+活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150611,None,E
1122,150250.SZ,银行B端,招商基金,中信银行,股票型,20150520,20201231,20150528,20150504,20210104,...,0.10,None,中证银行指数收益率*95%+金融机构人民币活期存款基准利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150528,None,E
1123,150249.SZ,银行A端,招商基金,中信银行,股票型,20150520,20201231,20150528,20150504,20210104,...,0.10,None,中证银行指数收益率*95%+金融机构人民币活期存款基准利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150528,None,E
1144,150241.SZ,银行A级,富国基金,中国农业银行,股票型,20150430,20190509,20150513,20150416,20190510,...,0.01,None,中证银行指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150513,None,E
1145,150242.SZ,银行B级,富国基金,中国农业银行,股票型,20150430,20190509,20150513,20150416,20190510,...,0.01,None,中证银行指数收益率*95%+银行人民币活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150513,None,E
1150,150228.SZ,银行B,鹏华基金,中国建设银行,股票型,20150417,20201231,20150428,20150407,20210104,...,0.10,None,中证银行指数收益率*95%+商业银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150428,None,E
1151,150227.SZ,银行A,鹏华基金,中国建设银行,股票型,20150417,20201231,20150428,20150407,20210104,...,0.10,None,中证银行指数收益率*95%+商业银行活期存款利率(税后)*5%,D,被动指数型,契约型封闭式,None,20150428,None,E
1152,160631.SZ,银行LOF基金,鹏华基金,中国建设银行,股票型,20150417,None,20210118,20150407,None,...,0.10,None,中证银行指数收益率*95%+商业银行活期存款利率(税后)*5%,L,被动指数型,契约型开放式,None,20150428,20150428,E

In [125]:
get_latest_holding('512800.SH','20220930',stock_code_name)

      ts_code    code           mkv       amount  stk_mkv_ratio     name
0   512800.SH  600036  1.255188e+09   37301283.0          13.98     招商银行
1   512800.SH  601166  1.032323e+09   62001382.0          11.50     兴业银行
2   512800.SH  601398  6.506872e+08  149583273.0           7.25     工商银行
3   512800.SH  601328  5.415833e+08  117225827.0           6.03     交通银行
4   512800.SH  601288  3.898099e+08  136297162.0           4.34     农业银行
5   512800.SH  600919  3.748861e+08   50387920.0           4.18     江苏银行
6   512800.SH  600016  3.590567e+08  105916420.0           4.00     民生银行
7   512800.SH  600000  3.533991e+08   50198737.0           3.94     浦发银行
8   512800.SH  688073  2.238720e+05       2544.0           0.00     毕得医药
9   512800.SH  688322  1.878939e+05       8529.0           0.00  奥比中光-UW
10  512800.SH  688381  2.236576e+05       7362.0           0.00      帝奥微
11  512800.SH  688382  3.624421e+05      36208.0           0.00   益方生物-U
12  512800.SH  688459  2.343772e+05      17259.0           0.00     哈铁科技

In [136]:
# get_latest_holding('515290.SH','20220930',stock_code_name)

## 军工ETF

In [127]:
fund_list_E.query('name.str.contains("军工") and name.str.contains("ETF")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
649,512710.SH,军工龙头ETF,富国基金,中国建设银行,股票型,20190723,None,20190826,20190524,None,...,0.1,None,中证军工龙头指数收益率,L,被动指数型,契约型开放式,None,20190826,20190826,E
811,512560.SH,军工ETF易方达,易方达基金,招商银行,股票型,20170714,None,20170728,20170609,None,...,0.1,None,中证军工指数,L,被动指数型,契约型开放式,None,20170728,20170728,E
904,512680.SH,军工ETF基金,广发基金,中国工商银行,股票型,20160830,None,20161014,20160725,None,...,0.1,None,中证军工指数收益率,L,被动指数型,契约型开放式,None,20161014,20161014,E
910,512810.SH,国防军工ETF,华宝基金,中国建设银行,股票型,20160805,None,20160822,20160711,None,...,0.1,None,中证军工指数,L,被动指数型,契约型开放式,None,20160822,20160822,E
918,512660.SH,军工ETF,国泰基金,中国建设银行,股票型,20160726,None,20160808,20160620,None,...,0.1,None,中证军工指数收益率,L,被动指数型,契约型开放式,None,20160808,20160808,E

In [132]:
get_latest_holding('513330.SH','20220930',stock_code_name)

Empty DataFrame
Columns: [ts_code, code, mkv, amount, stk_mkv_ratio, name]
Index: []

In [133]:
pro.fund_daily(ts_code='150018.SZ', start_date='20180101', end_date='20181029')

,ts_code,trade_date,pre_close,open,high,low,close,change,pct_chg,vol,amount
0,150018.SZ,20181029,0.986,0.986,0.987,0.984,0.986,0.000,0.0000,893739.59,88075.423
1,150018.SZ,20181026,0.984,0.983,0.987,0.983,0.986,0.002,0.2033,994975.67,98039.003
2,150018.SZ,20181025,0.982,0.983,0.985,0.982,0.984,0.002,0.2037,1237602.70,121757.884
3,150018.SZ,20181024,0.983,0.982,0.984,0.981,0.982,-0.001,-0.1017,587794.10,57767.413
4,150018.SZ,20181023,0.978,0.977,0.984,0.977,0.983,0.005,0.5112,583652.61,57220.019
...,...,...,...,...,...,...,...,...,...,...,...
193,150018.SZ,20180109,0.881,0.881,0.884,0.880,0.884,0.003,0.3405,140868.21,12432.708
194,150018.SZ,20180108,0.881,0.880,0.882,0.880,0.881,0.000,0.0000,285399.14,25143.157
195,150018.SZ,20180105,0.900,0.881,0.882,0.880,0.881,-0.019,-2.1111,331175.53,29157.982
196,150018.SZ,20180104,1.000,0.900,0.900,0.900,0.900,-0.100,-10.0000,113223.00,10190.070
197,150018.SZ,20180102,0.923,0.923,0.925,0.922,0.923,0.000,0.0000,171839.95,15872.837

In [137]:
get_latest_holding('512710.SH','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio    name
0  512710.SH  600893  3.842458e+08  9159615.0           9.50    航发动力
1  512710.SH  600760  3.283243e+08  5386781.0           8.11    中航沈飞
2  512710.SH  688122  2.056049e+08  1923519.0           5.08    西部超导
3  512710.SH  600765  1.820815e+08  6077485.0           4.50    中航重机
4  512710.SH  600862  1.419938e+08  5748738.0           3.51    中航高科
5  512710.SH  688348  3.233448e+06     5644.0           0.08    昱能科技
6  512710.SH  688072  1.545268e+06     5300.0           0.04  拓荆科技-U
7  512710.SH  688073  2.238720e+05     2544.0           0.01    毕得医药
8  512710.SH  688409  4.433167e+05     6334.0           0.01    富创精密
9  512710.SH  688459  2.343772e+05    17259.0           0.01    哈铁科技

## 上证50eft

In [9]:
df = pro.fund_portfolio(ts_code='510050.SH') #证券ETF
df['code'] = df['symbol'].map(lambda x: x.replace('.SH','').replace('.SZ','').replace('.BJ',''))

df.query('end_date == "20220630"').sort_values(by='stk_mkv_ratio',ascending = 0)
# df

,ts_code,ann_date,end_date,symbol,mkv,amount,stk_mkv_ratio,stk_float_ratio
1,510050.SH,20220720,20220630,600519.SH,8.798081e+09,4302240.0,16.83,0.34
0,510050.SH,20220720,20220630,600036.SH,3.580432e+09,84844361.0,6.85,0.41
6,510050.SH,20220720,20220630,601318.SH,3.467315e+09,74262479.0,6.63,0.69
8,510050.SH,20220720,20220630,601012.SH,2.769368e+09,41563375.0,5.30,0.55
5,510050.SH,20220720,20220630,601166.SH,1.983757e+09,99686275.0,3.79,0.48
4,510050.SH,20220720,20220630,600900.SH,1.802284e+09,77953451.0,3.45,0.34
7,510050.SH,20220720,20220630,601888.SH,1.557102e+09,6684851.0,2.98,0.34
9,510050.SH,20220720,20220630,603259.SH,1.461519e+09,14054415.0,2.80,0.55
3,510050.SH,20220720,20220630,600030.SH,1.449263e+09,66909640.0,2.77,0.59
2,510050.SH,20220720,20220630,600887.SH,1.366932e+09,35094528.0,2.61,0.56
10,510050.SH,20220830,20220630,601398.SH,1.146057e+09,240263553.0,2.19,0.09
11,510050.SH,20220830,20220630,600276.SH,1.135345e+09,30610538.0,2.17,0.48
12,510050.SH,20220830,20220630,600438.SH,1.108598e+09,18519852.0,2.12,0.41
13,510050.SH,20220830,20220630,600809.SH,1.087790e+09,3349106.0,2.08,0.28
14,510050.SH,20220830,20220630,600309.SH,1.044286e+09,10766943.0,2.00,0.34
15,510050.SH,20220830,20220630,601899.SH,9.219410e+08,98814685.0,1.76,0.48
16,510050.SH,20220830,20220630,603288.SH,8.610834e+08,9529475.0,1.65,0.21
17,510050.SH,20220830,20220630,600048.SH,8.597100e+08,49238830.0,1.64,0.41
18,510050.SH,20220830,20220630,603799.SH,8.342148e+08,8724271.0,1.60,0.55
19,510050.SH,20220830,20220630,600031.SH,7.767325e+08,40751969.0,1.49,0.48
20,510050.SH,20220830,20220630,601668.SH,7.646399e+08,143729303.0,1.46,0.35
21,510050.SH,20220830,20220630,601088.SH,7.529917e+08,22612364.0,1.44,0.14
22,510050.SH,20220830,20220630,600436.SH,7.372371e+08,2066653.0,1.41,0.34
23,510050.SH,20220830,20220630,600690.SH,7.122777e+08,25938736.0,1.36,0.41
24,510050.SH,20220830,20220630,601288.SH,6.609048e+08,218842644.0,1.26,0.07
25,510050.SH,20220830,20220630,603986.SH,6.494576e+08,4566891.0,1.24,0.69
26,510050.SH,20220830,20220630,600837.SH,6.493634e+08,66194024.0,1.24,0.75
27,510050.SH,20220830,20220630,603501.SH,6.242985e+08,3608036.0,1.19,0.46
28,510050.SH,20220830,20220630,601919.SH,6.031685e+08,43393420.0,1.15,0.34
29,510050.SH,20220830,20220630,600585.SH,5.805960e+08,16456803.0,1.11,0.41
30,510050.SH,20220830,20220630,601688.SH,5.728960e+08,40344786.0,1.10,0.55
31,510050.SH,20220830,20220630,600104.SH,5.706404e+08,32040447.0,1.09,0.27
32,510050.SH,20220830,20220630,601601.SH,5.519492e+08,23457254.0,1.06,0.34
33,510050.SH,20220830,20220630,600111.SH,5.254959e+08,14945845.0,1.01,0.41
34,510050.SH,20220830,20220630,601211.SH,4.688601e+08,30846062.0,0.90,0.42
35,510050.SH,20220830,20220630,600745.SH,4.350430e+08,5111538.0,0.83,0.55
36,510050.SH,20220830,20220630,600893.SH,4.159401e+08,9139532.0,0.80,0.39
37,510050.SH,20220830,20220630,600028.SH,3.735170e+08,91548276.0,0.71,0.10
38,510050.SH,20220830,20220630,600905.SH,3.697048e+08,58776603.0,0.71,0.69
39,510050.SH,20220830,20220630,600010.SH,3.672230e+08,156265100.0,0.70,0.49
40,510050.SH,20220830,20220630,600196.SH,3.639654e+08,8255055.0,0.70,0.41
41,510050.SH,20220830,20220630,601628.SH,3.542158e+08,11396904.0,0.68,0.05
42,510050.SH,20220830,20220630,601857.SH,3.524219e+08,66494699.0,0.67,0.04
43,510050.SH,20220830,20220630,600570.SH,3.483081e+08,7999727.0,0.67,0.55
44,510050.SH,20220830,20220630,600346.SH,3.216242e+08,14461520.0,0.62,0.21
45,510050.SH,20220830,20220630,601633.SH,3.121473e+08,8427302.0,0.60,0.14
46,510050.SH,20220830,20220630,601066.SH,2.576061e+08,8910623.0,0.49,0.23
47,510050.SH,20220830,20220630,600588.SH,2.522429e+08,11618741.0,0.48,0.36
48,510050.SH,20220830,20220630,601995.SH,1.779694e+08,4000211.0,0.34,0.43
49,510050.SH,20220830,20220630,601728.SH,1.387878e+08,37208522.0,0.27,0.69
50,510050.SH,20220830,20220630,600941.SH,5.264494e+06,87363.0,0.01,0.02
51,510050.SH,20220830,20220630,600938.SH,1.332303e+06,84004.0,0.00,0.01
52,510050.SH,20220830,20220630,688326.SH,9.159662e+05,6832.0,0.00,0.03
53,510050.SH,20220830,20220630,688220.SH,8.485269e+05,12371.0,0.00,0.04
54,510050.SH,20220830,20220630,688176.SH,4.760147e+05,37990.0,0.00,0.04
55,510050.SH,20220830,20220630,688322.SH,2.643137e+05,8529.0,0.00,0.03
56,510050.SH,20220830,20220630,688125.SH,1.639048e+05,3774.0,0.00,0.02
57,510050.SH,20220830,20220630,688173.SH,1.339423e+05,4236.0,0.00,0.01
58,510050.SH,20220830,20220630,601089.SH,3.681645e+04,1749.0,0.00,0.00

## 沪深300etf

In [10]:
df = pro.fund_portfolio(ts_code='510300.SH') #证券ETF
df['code'] = df['symbol'].map(lambda x: x.replace('.SH','').replace('.SZ','').replace('.BJ',''))

df.query('end_date == "20220630"').sort_values(by='stk_mkv_ratio',ascending = 0)
# df

,ts_code,ann_date,end_date,symbol,mkv,amount,stk_mkv_ratio,stk_float_ratio
49,510300.SH,20220721,20220630,600519.SH,2.908131e+09,1422069.0,6.11,0.11
63,510300.SH,20220721,20220630,300750.SZ,1.699555e+09,3182687.0,3.57,0.16
50,510300.SH,20220721,20220630,600036.SH,1.184124e+09,28059802.0,2.49,0.14
61,510300.SH,20220721,20220630,601318.SH,1.145997e+09,24544806.0,2.41,0.23
56,510300.SH,20220721,20220630,601012.SH,9.153681e+08,13738077.0,1.92,0.18
...,...,...,...,...,...,...,...,...
191,510300.SH,20220830,20220630,301158.SZ,7.724020e+03,379.0,0.00,0.00
159,510300.SH,20220830,20220630,601089.SH,3.681645e+04,1749.0,0.00,0.00
160,510300.SH,20220830,20220630,301200.SZ,4.449544e+04,857.0,0.00,0.00
188,510300.SH,20220830,20220630,301279.SZ,6.751760e+03,296.0,0.00,0.00
173,510300.SH,20220830,20220630,301259.SZ,1.204602e+04,483.0,0.00,0.00

## 医药

### 医药卫生ETF

In [143]:
get_latest_holding('159938.SZ','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio  name
0  159938.SZ  600276  1.765509e+08  5029941.0           5.56  恒瑞医药
1  159938.SZ  603259  1.658116e+08  2312897.0           5.22  药明康德
2  159938.SZ  600436  9.119944e+07   341827.0           2.87   片仔癀

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
1310,512010.SH,医药ETF,易方达基金,中国建设银行,股票型,20130923,None,20131028,20130826,None,...,0.1,None,沪深300医药卫生指数,L,被动指数型,契约型开放式,None,20131028,20131028,E

### 医药ETF

In [144]:
get_latest_holding('512010.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512010.SH  600276  1.245080e+09  35472360.0          11.33  恒瑞医药
1  512010.SH  603259  1.168766e+09  16303056.0          10.64  药明康德
2  512010.SH  600436  6.421457e+08   2406843.0           5.84   片仔癀

### 生物医药ETF

In [157]:
get_latest_holding('512290.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio   name
0  512290.SH  600276  6.853648e+08  19526064.0          16.88   恒瑞医药
1  512290.SH  603259  4.913337e+08   6853588.0          12.10   药明康德
2  512290.SH  688185  8.741887e+07    722470.0           2.15    康希诺
3  512290.SH  688041  3.445284e+06     67317.0           0.08   海光信息
4  512290.SH  688073  2.238720e+05      2544.0           0.01   毕得医药
5  512290.SH  688213  5.379618e+05     14046.0           0.01  思特威-W
6  512290.SH  688409  4.433167e+05      6334.0           0.01   富创精密

### 生物科技ETF

In [160]:
get_latest_holding('159837.SZ','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio  name
0  159837.SZ  600276  2.046159e+08  5829514.0          12.81  恒瑞医药
1  159837.SZ  603259  1.296233e+08  1808109.0           8.11  药明康德
2  159837.SZ  600196  6.329647e+07  2141288.0           3.96  复星医药

In [145]:
get_latest_holding('159883.SZ','20220930',stock_code_name)

     ts_code    code         mkv    amount  stk_mkv_ratio  name
0  159883.SZ  603392  35105356.0  306865.0           3.35  万泰生物
1  159883.SZ  603882  30365358.0  479100.0           2.90  金域医学

In [146]:
get_latest_holding('512170.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512170.SH  603259  1.279080e+09  17841819.0           8.19  药明康德
1  512170.SH  600763  4.806711e+08   3755243.0           3.08  通策医疗
2  512170.SH  688275  8.218652e+05      4399.0           0.01  万润新能
3  512170.SH  688045  1.837150e+05      3939.0           0.00   必易微
4  512170.SH  688048  7.367150e+05      6790.0           0.00  长光华芯
5  512170.SH  688073  2.238720e+05      2544.0           0.00  毕得医药
6  512170.SH  688459  2.343772e+05     17259.0           0.00  哈铁科技

## 第一产业

### 养殖ETF

In [183]:
fund_list_E[fund_list_E.ts_code.str.contains('159865')]

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
390,159865.SZ,养殖ETF,国泰基金,浙商银行,股票型,20210301,None,20210308,20210223,None,...,0.1,None,中证畜牧养殖指数收益率,L,被动指数型,契约型开放式,None,20210308,20210308,E

In [147]:
get_latest_holding('159865.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio    name
0  159865.SZ  600201  1.087846e+08  13911070.0           3.03    生物股份
1  159865.SZ  600195  9.892897e+07   7517399.0           2.75    中牧股份
2  159865.SZ  603609  1.049481e+06    112244.0           0.03    禾丰股份
3  159865.SZ  688326  1.197171e+06      6832.0           0.03  经纬恒润-W
4  159865.SZ  688428  6.440770e+05     70700.0           0.02  诺诚健华-U
5  159865.SZ  688375  5.043805e+05      6110.0           0.01    国博电子

### 农业

In [182]:
get_latest_holding('159825.SZ','20220930',stock_code_name)

     ts_code    code          mkv     amount  stk_mkv_ratio    name
0  159825.SZ  600887  91258958.00  2767100.0           4.82    伊利股份
1  159825.SZ  600096  71972496.75  3032975.0           3.80     云天化
2  159825.SZ  600141  61668419.04  1841948.0           3.26    兴发集团
3  159825.SZ  688348   3233447.60     5644.0           0.17    昱能科技
4  159825.SZ  688072   1545268.00     5300.0           0.08  拓荆科技-U
5  159825.SZ  688114    520740.24     5336.0           0.03    华大智造
6  159825.SZ  688409    443316.66     6334.0           0.02    富创精密
7  159825.SZ  688459    234377.22    17259.0           0.01    哈铁科技

## 新能源车

### 新能源车ETF

In [162]:
fund_list_E.query('ts_code.str.contains("515030")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
562,515030.SH,新能源车ETF,华夏基金,中国银行,股票型,20200220,None,20200304,20200203,None,...,0.1,None,中证新能源汽车指数收益率,L,被动指数型,契约型开放式,None,20200304,20200304,E

In [149]:
get_latest_holding('515030.SH','20220930',stock_code_name)

     ts_code    code          mkv     amount  stk_mkv_ratio  name
0  515030.SH  603799  434572627.1  6754315.0           4.68  华友钴业

### 新能车ETF 2

In [165]:
fund_list_E.query('ts_code.str.contains("515700")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
576,515700.SH,新能车ETF,平安基金,招商证券,股票型,20191231,None,20200210,20191209,None,...,0.1,None,中证新能源汽车产业指数收益率,L,被动指数型,契约型开放式,None,20200210,20200210,E

In [150]:
get_latest_holding('515700.SH','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio    name
0  515700.SH  603799  2.412756e+08  3750009.0           4.45    华友钴业
1  515700.SH  688380  2.799082e+05    12677.0           0.01    中微半导
2  515700.SH  688073  2.238720e+05     2544.0           0.00    毕得医药
3  515700.SH  688137  1.954199e+05     2588.0           0.00    近岸蛋白
4  515700.SH  688373  2.053458e+05    31886.0           0.00  盟科药业-U

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
269,159766.SZ,旅游ETF,富国基金,中国银行,股票型,20210715,None,20210723,20210701,None,...,0.1,None,中证旅游主题指数收益率,L,被动指数型,契约型开放式,None,20210723,20210723,E

### 锂电池ETF

In [163]:
fund_list_E.query('ts_code.str.contains("561160")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
62,561160.SH,锂电池ETF,富国基金,中国农业银行,股票型,20220630,None,20220708,20220614,None,...,0.1,None,中证电池主题指数收益率,L,被动指数型,契约型开放式,None,20220708,20220708,E

In [164]:
get_latest_holding('561160.SH','20220930',stock_code_name)

     ts_code    code          mkv    amount  stk_mkv_ratio    name
0  561160.SH  603659  18016704.00  322880.0           2.95     璞泰来
1  561160.SH  688271    671008.32    4198.0           0.11    联影医疗
2  561160.SH  688428    599684.78   69569.0           0.10  诺诚健华-U
3  561160.SH  688459    234377.22   17259.0           0.04    哈铁科技
4  561160.SH  688409    239365.80    3420.0           0.04    富创精密

## 服务业

### 旅游ETF

In [167]:
fund_list_E.query('ts_code.str.contains("159766")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
269,159766.SZ,旅游ETF,富国基金,中国银行,股票型,20210715,None,20210723,20210701,None,...,0.1,None,中证旅游主题指数收益率,L,被动指数型,契约型开放式,None,20210723,20210723,E

In [170]:
get_latest_holding('159766.SZ','20220930',stock_code_name)

      ts_code    code           mkv      amount  stk_mkv_ratio  name
0   159766.SZ  601888  3.128980e+08   1578300.0          15.67  中国中免
1   159766.SZ  600754  2.476408e+08   4295591.0          12.40  锦江酒店
2   159766.SZ  600009  1.964289e+08   3399600.0           9.84  上海机场
3   159766.SZ  600029  1.193137e+08  17968933.0           5.98  南方航空
4   159766.SZ  600258  1.128665e+08   5276600.0           5.65  首旅酒店
5   159766.SZ  601111  1.106156e+08  10565000.0           5.54  中国国航
6   159766.SZ  600115  9.438408e+07  19341000.0           4.73  中国东航
7   159766.SZ  601021  6.678574e+07   1289300.0           3.34  春秋航空
8   159766.SZ  688114  5.207402e+05      5336.0           0.03  华大智造
9   159766.SZ  688409  4.433167e+05      6334.0           0.02  富创精密
10  159766.SZ  688381  2.236576e+05      7362.0           0.01   帝奥微
11  159766.SZ  688459  2.343772e+05     17259.0           0.01  哈铁科技

## 可选消费

### 医药卫生ETF

In [186]:
get_latest_holding('512010.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512010.SH  600276  1.245080e+09  35472360.0          11.33  恒瑞医药
1  512010.SH  603259  1.168766e+09  16303056.0          10.64  药明康德
2  512010.SH  600436  6.421457e+08   2406843.0           5.84   片仔癀

### 医药ETF

In [187]:
get_latest_holding('512010.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512010.SH  600276  1.245080e+09  35472360.0          11.33  恒瑞医药
1  512010.SH  603259  1.168766e+09  16303056.0          10.64  药明康德
2  512010.SH  600436  6.421457e+08   2406843.0           5.84   片仔癀

### 医疗ETF

In [191]:
get_latest_holding('512170.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  512170.SH  603259  1.279080e+09  17841819.0           8.19  药明康德
1  512170.SH  600763  4.806711e+08   3755243.0           3.08  通策医疗
2  512170.SH  688275  8.218652e+05      4399.0           0.01  万润新能
3  512170.SH  688045  1.837150e+05      3939.0           0.00   必易微
4  512170.SH  688048  7.367150e+05      6790.0           0.00  长光华芯
5  512170.SH  688073  2.238720e+05      2544.0           0.00  毕得医药
6  512170.SH  688459  2.343772e+05     17259.0           0.00  哈铁科技

### 生物医药ETF

In [188]:
get_latest_holding('512290.SH','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio   name
0  512290.SH  600276  6.853648e+08  19526064.0          16.88   恒瑞医药
1  512290.SH  603259  4.913337e+08   6853588.0          12.10   药明康德
2  512290.SH  688185  8.741887e+07    722470.0           2.15    康希诺
3  512290.SH  688041  3.445284e+06     67317.0           0.08   海光信息
4  512290.SH  688073  2.238720e+05      2544.0           0.01   毕得医药
5  512290.SH  688213  5.379618e+05     14046.0           0.01  思特威-W
6  512290.SH  688409  4.433167e+05      6334.0           0.01   富创精密

### 生物科技ETF

In [189]:
get_latest_holding('159837.SZ','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio  name
0  159837.SZ  600276  2.046159e+08  5829514.0          12.81  恒瑞医药
1  159837.SZ  603259  1.296233e+08  1808109.0           8.11  药明康德
2  159837.SZ  600196  6.329647e+07  2141288.0           3.96  复星医药

### 家电ETF

In [190]:
get_latest_holding('159736.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  159736.SZ  600519  7.700375e+08    411235.0          10.57  贵州茅台
1  159736.SZ  600887  6.729300e+08  20404184.0           9.24  伊利股份
2  159736.SZ  600809  6.039627e+08   1994000.0           8.29  山西汾酒
3  159736.SZ  603288  4.705910e+08   5682094.0           6.46  海天味业
4  159736.SZ  600600  1.538201e+08   1448400.0           2.11  青岛啤酒
5  159736.SZ  688297  1.537142e+06     37246.0           0.02  中无人机
6  159736.SZ  688275  8.989796e+05      4399.0           0.01  万润新能
7  159736.SZ  688409  4.433167e+05      6334.0           0.01  富创精密
8  159736.SZ  688403  1.601124e+05     18553.0           0.00  汇成股份

## 日常消费

### 酒ETF

In [179]:
get_latest_holding('512690.SH','20220930',stock_code_name)

     ts_code    code           mkv     amount  stk_mkv_ratio  name
0  512690.SH  600519  1.630333e+09   870672.0          16.31  贵州茅台
1  512690.SH  600809  1.102567e+09  3640155.0          11.03  山西汾酒
2  512690.SH  600600  4.496323e+08  4233826.0           4.50  青岛啤酒
3  512690.SH  603369  3.394103e+08  7397783.0           3.40   今世缘
4  512690.SH  600132  3.067771e+08  2734199.0           3.07  重庆啤酒
5  512690.SH  688120  1.515121e+06     4822.0           0.02  华海清科
6  512690.SH  688048  7.367150e+05     6790.0           0.01  长光华芯
7  512690.SH  688053  2.975920e+05     4865.0           0.00   思科瑞
8  512690.SH  688409  4.433167e+05     6334.0           0.00  富创精密

### 消费ETF

In [177]:
get_latest_holding('159928.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio    name
0  159928.SZ  600519  1.058966e+09    565536.0          10.28    贵州茅台
1  159928.SZ  600887  8.505609e+08  25790204.0           8.26    伊利股份
2  159928.SZ  600809  7.443716e+08   2457564.0           7.23    山西汾酒
3  159928.SZ  603288  5.794926e+08   6997013.0           5.63    海天味业
4  159928.SZ  688114  5.714856e+05      5336.0           0.01    华大智造
5  159928.SZ  688073  2.238720e+05      2544.0           0.00    毕得医药
6  159928.SZ  688153  2.627578e+05      7674.0           0.00  唯捷创芯-U
7  159928.SZ  688409  4.433167e+05      6334.0           0.00    富创精密
8  159928.SZ  688459  2.343772e+05     17259.0           0.00    哈铁科技

### 饮食ETF

In [178]:
get_latest_holding('159736.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  159736.SZ  600519  7.700375e+08    411235.0          10.57  贵州茅台
1  159736.SZ  600887  6.729300e+08  20404184.0           9.24  伊利股份
2  159736.SZ  600809  6.039627e+08   1994000.0           8.29  山西汾酒
3  159736.SZ  603288  4.705910e+08   5682094.0           6.46  海天味业
4  159736.SZ  600600  1.538201e+08   1448400.0           2.11  青岛啤酒
5  159736.SZ  688297  1.537142e+06     37246.0           0.02  中无人机
6  159736.SZ  688275  8.989796e+05      4399.0           0.01  万润新能
7  159736.SZ  688409  4.433167e+05      6334.0           0.01  富创精密
8  159736.SZ  688403  1.601124e+05     18553.0           0.00  汇成股份

### 家电ETF

In [184]:
get_latest_holding('159996.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio    name
0  159996.SZ  600690  3.133016e+08  12648430.0          14.79    海尔智家
1  159996.SZ  605117  1.276955e+08    303885.0           6.03    德业股份
2  159996.SZ  688169  7.946937e+07    307818.0           3.75    石头科技
3  159996.SZ  603486  6.067526e+07    909674.0           2.86     科沃斯
4  159996.SZ  688696  4.324210e+07    206900.0           2.04    极米科技
5  159996.SZ  600938  1.295342e+06     84004.0           0.06    中国海油
6  159996.SZ  688409  4.433167e+05      6334.0           0.02    富创精密
7  159996.SZ  688073  2.238720e+05      2544.0           0.01    毕得医药
8  159996.SZ  688373  2.053458e+05     31886.0           0.01  盟科药业-U
9  159996.SZ  688392  2.872917e+05      2745.0           0.01    骄成超声

## 能源

In [172]:
fund_list_E.query('ts_code.str.contains("159611")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
134,159611.SZ,电力ETF,广发基金,中国建设银行,股票型,20211229,None,20220107,20211220,None,...,0.1,None,中证全指电力公用事业指数收益率,L,被动指数型,契约型开放式,None,20220107,20220107,E

### 煤炭

In [139]:
get_latest_holding('515220.SH','20220930',stock_code_name)

      ts_code    code           mkv       amount  stk_mkv_ratio  name
0   515220.SH  601225  5.441513e+08   23897729.0          11.54  陕西煤业
1   515220.SH  600188  4.933711e+08    9833986.0          10.47  兖矿能源
2   515220.SH  601088  4.269875e+08   13495181.0           9.06  中国神华
3   515220.SH  600157  3.777848e+08  242169757.0           8.01  永泰能源
4   515220.SH  600348  2.382959e+08   13043017.0           5.06  华阳股份
5   515220.SH  601699  2.225584e+08   13184741.0           4.72  潞安环能
6   515220.SH  601898  2.118308e+08   19908910.0           4.49  中煤能源
7   515220.SH  600546  1.971688e+08   10899323.0           4.18  山煤国际
8   515220.SH  600938  1.295342e+06      84004.0           0.03  中国海油
9   515220.SH  688114  5.207402e+05       5336.0           0.01  华大智造
10  515220.SH  688400  2.706110e+05      13111.0           0.01   凌云光
11  515220.SH  688409  4.433167e+05       6334.0           0.01  富创精密
12  515220.SH  688073  2.238720e+05       2544.0           0.00  毕得医药

### 电力ETF

In [174]:
get_latest_holding('159611.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  159611.SZ  600900  1.629185e+08   7164400.0           9.84  长江电力
1  159611.SZ  601985  1.450882e+08  24801400.0           8.77  中国核电
2  159611.SZ  600905  1.285791e+08  22838200.0           7.77  三峡能源
3  159611.SZ  600795  9.654733e+07  23721703.0           5.83  国电电力
4  159611.SZ  600011  8.881615e+07  11701733.0           5.37  华能国际
5  159611.SZ  600886  8.518861e+07   7931900.0           5.15  国投电力
6  159611.SZ  600674  5.640386e+07   4688600.0           3.41  川投能源
7  159611.SZ  600027  5.161208e+07   8674300.0           3.12  华电国际

In [192]:
get_latest_holding('159930.SZ','20220930',stock_code_name)

     ts_code    code          mkv      amount  stk_mkv_ratio  name
0  159930.SZ  601225  62986920.48   2766224.0          14.74  陕西煤业
1  159930.SZ  601088  57338229.48   1812207.0          13.41  中国神华
2  159930.SZ  600028  40926634.32   9540008.0           9.58  中国石化
3  159930.SZ  600256  40245551.00   3277325.0           9.42  广汇能源
4  159930.SZ  601857  35534206.98   6926746.0           8.31  中国石油
5  159930.SZ  600188  32671958.25    651225.0           7.64  兖矿能源
6  159930.SZ  600157  24713988.00  15842300.0           5.78  永泰能源
7  159930.SZ  600348  15651909.00    856700.0           3.66  华阳股份
8  159930.SZ  601699  14391297.20    852565.0           3.37  潞安环能

     ts_code    code          mkv     amount  stk_mkv_ratio    name
0  159825.SZ  600887  91258958.00  2767100.0           4.82    伊利股份
1  159825.SZ  600096  71972496.75  3032975.0           3.80     云天化
2  159825.SZ  600141  61668419.04  1841948.0           3.26    兴发集团
3  159825.SZ  688348   3233447.60     5644.0           0.17    昱能科技
4  159825.SZ  688072   1545268.00     5300.0           0.08  拓荆科技-U
5  159825.SZ  688114    520740.24     5336.0           0.03    华大智造
6  159825.SZ  688409    443316.66     6334.0           0.02    富创精密
7  159825.SZ  688459    234377.22    17259.0           0.01    哈铁科技

## 其他

### 兴全合宜LOF

In [176]:
fund_list_E.query('ts_code.str.contains("163417")',engine='python')

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
768,163417.SZ,兴全合宜LOF,兴证全球基金,招商银行,混合型,20180123,None,20180423,20180116,None,...,0.1,None,沪深300指数收益率*60%+恒生指数收益率*20%+中国债券总指数收益率*20%,L,灵活配置型,契约型开放式,None,20200213,20200213,E

In [175]:
get_latest_holding('163417.SZ','20220930',stock_code_name)

     ts_code    code           mkv      amount  stk_mkv_ratio  name
0  163417.SZ  600690  1.106701e+09  44679094.0           6.87  海尔智家
1  163417.SZ  600703  6.609802e+08  37813512.0           4.10  三安光电
2  163417.SZ  600873  6.153610e+08  60746400.0           3.82  梅花生物
3  163417.SZ  603707  5.728261e+08  34424646.0           3.56  健友股份
4  163417.SZ  688099  5.164328e+08   7975563.0           3.21  晶晨股份

In [141]:
get_latest_holding('512980.SH','20220930',stock_code_name)

     ts_code    code          mkv      amount  stk_mkv_ratio  name
0  512980.SH  600637  149304468.6  24396155.0           3.36  东方明珠

In [2]:
level_2_index = pro.index_classify(level='L2',src='SW2021')

In [3]:
level_2_index

    index_code industry_name level industry_code is_pub parent_code
0    801016.SI           种植业    L2        110100      1      110000
1    801015.SI            渔业    L2        110200      1      110000
2    801011.SI           林业Ⅱ    L2        110300      0      110000
3    801014.SI            饲料    L2        110400      1      110000
4    801012.SI         农产品加工    L2        110500      1      110000
..         ...           ...   ...           ...    ...         ...
129  801971.SI          环境治理    L2        760100      1      760000
130  801972.SI         环保设备Ⅱ    L2        760200      1      760000
131  801981.SI          个护用品    L2        770100      1      770000
132  801982.SI           化妆品    L2        770200      1      770000
133  801983.SI          医疗美容    L2        770300      0      770000

[134 rows x 6 columns]