In [1]:
import tushare as ts
token = "488917d460bca13177c0b510492fc5fc04d0629bc76cc32a4f73fcf0"
ts.set_token(token)
pro = ts.pro_api()

In [14]:
import QUANTAXIS as QA
import pandas as pd

In [12]:
level_2_index = pro.index_classify(level='L2',src='SW2021')

In [13]:
level_2_index

    index_code industry_name level industry_code is_pub parent_code
0    801016.SI           种植业    L2        110100      1      110000
1    801015.SI            渔业    L2        110200      1      110000
2    801011.SI           林业Ⅱ    L2        110300      0      110000
3    801014.SI            饲料    L2        110400      1      110000
4    801012.SI         农产品加工    L2        110500      1      110000
..         ...           ...   ...           ...    ...         ...
129  801971.SI          环境治理    L2        760100      1      760000
130  801972.SI         环保设备Ⅱ    L2        760200      1      760000
131  801981.SI          个护用品    L2        770100      1      770000
132  801982.SI           化妆品    L2        770200      1      770000
133  801983.SI          医疗美容    L2        770300      0      770000

[134 rows x 6 columns]

In [11]:
index_all

    index_code industry_name level industry_code is_pub parent_code
0    801010.SI          农林牧渔    L1        110000      1           0
1    801030.SI          基础化工    L1        220000      1           0
2    801040.SI            钢铁    L1        230000      1           0
3    801050.SI          有色金属    L1        240000      1           0
4    801080.SI            电子    L1        270000      1           0
..         ...           ...   ...           ...    ...         ...
506  859812.SI          洗护用品    L3        770102      0      770100
507  859821.SI      化妆品制造及其他    L3        770201      1      770200
508  859822.SI         品牌化妆品    L3        770202      1      770200
509  859831.SI          医美耗材    L3        770301      0      770300
510  859832.SI          医美服务    L3        770302      0      770300

[511 rows x 6 columns]

In [2]:
dir(ts)

['MailMerge',
 'TraderAPI',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'bar',
 'bdi',
 'broker_tops',
 'cap_tops',
 'close_apis',
 'codecs',
 'coins',
 'coins_bar',
 'coins_snapshot',
 'coins_tick',
 'coins_trade',
 'day_boxoffice',
 'day_cinema',
 'forecast_data',
 'fund',
 'fund_holdings',
 'futures',
 'get_apis',
 'get_area_classified',
 'get_balance_sheet',
 'get_cash_flow',
 'get_cashflow_data',
 'get_cffex_daily',
 'get_concept_classified',
 'get_cpi',
 'get_czce_daily',
 'get_day_all',
 'get_dce_daily',
 'get_debtpaying_data',
 'get_deposit_rate',
 'get_fund_info',
 'get_future_daily',
 'get_gdp_contrib',
 'get_gdp_for',
 'get_gdp_pull',
 'get_gdp_quarter',
 'get_gdp_year',
 'get_gem_classified',
 'get_gold_and_foreign_reserves',
 'get_growth_data',
 'get_h_data',
 'get_hist_data',
 'get_hists',
 'get_hs300s',
 'get_index',
 'get_industry_classified',
 'get_instrument',
 'get_intlfuture',
 'get_k_data',
 'get_latest_news',
 'get_loan_rate',
 'get_markets',
 'get_money_supply',
 'get_money_supply_bal',
 'get_nav_close',
 'get_nav_grading',
 'get_nav_history',
 'get_nav_open',
 'get_notices',
 'get_operation_data',
 'get_ppi',
 'get_profit_data',
 'get_profit_statement',
 'get_realtime_quotes',
 'get_report_data',
 'get_rrr',
 'get_shfe_daily',
 'get_shfe_vwap',
 'get_sina_dd',
 'get_sme_classified',
 'get_st_classified',
 'get_stock_basics',
 'get_suspended',
 'get_sz50s',
 'get_terminated',
 'get_tick_data',
 'get_today_all',
 'get_today_ticks',
 'get_token',
 'get_zz500s',
 'global_realtime',
 'guba_sina',
 'inst_detail',
 'inst_tops',
 'internet',
 'is_holiday',
 'latest_content',
 'lpr_data',
 'lpr_ma_data',
 'margin_detail',
 'margin_offset',
 'margin_target',
 'margin_zsl',
 'moneyflow_hsgt',
 'month_boxoffice',
 'new_cbonds',
 'new_stocks',
 'notice_content',
 'os',
 'pledged_detail',
 'pro',
 'pro_api',
 'pro_bar',
 'profit_data',
 'profit_divis',
 'quotes',
 'realtime_boxoffice',
 'reset_instrument',
 'set_token',
 'sh_margin_details',
 'sh_margins',
 'shibor_data',
 'shibor_ma_data',
 'shibor_quote_data',
 'stock',
 'stock_issuance',
 'stock_pledged',
 'subs',
 'sz_margin_details',
 'sz_margins',
 'tick',
 'top10_holders',
 'top_list',
 'trade_cal',
 'trader',
 'util',
 'xsg_data']