In [1]:
import tushare as ts
token = "488917d460bca13177c0b510492fc5fc04d0629bc76cc32a4f73fcf0"
ts.set_token(token)
pro = ts.pro_api()

In [3]:
import QUANTAXIS as QA
import pandas as pd
import numpy as np

In [5]:
fund_list =  pro.fund_basic(market='E')

In [6]:
fund_list

,ts_code,name,management,custodian,fund_type,found_date,due_date,list_date,issue_date,delist_date,...,min_amount,exp_return,benchmark,status,invest_type,type,trustee,purc_startdate,redm_startdate,market
0,508058.SH,中金厦门安居REIT,中金基金,兴业银行,REITs,20220822,None,20220831,20220816,None,...,0.1,None,None,L,None,契约型封闭式,None,None,None,E
1,180501.SZ,红土深圳安居REIT,红土创新基金,招商银行,REITs,20220822,None,20220831,20220816,None,...,0.1,None,None,L,None,契约型封闭式,None,None,None,E
2,508068.SH,华夏北京保障房REIT,华夏基金,中国建设银行,REITs,20220822,None,20220831,20220816,None,...,0.1,None,None,L,None,契约型封闭式,None,None,None,E
3,159637.SZ,新能源车龙头ETF,西藏东财基金,广发证券,股票型,20220819,None,20220901,20220801,None,...,0.1,None,中证新能源汽车指数收益率,I,被动指数型,契约型开放式,None,20220901,20220901,E
4,159631.SZ,中证100ETF招商,招商基金,中信证券,股票型,20220818,None,20220826,20220801,None,...,0.1,None,中证100指数收益率,L,被动指数型,契约型开放式,None,20220826,20220826,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1686,500019.SH,基金普润,鹏华基金,中国工商银行,股票型,19920509,20070424,20010904,None,20070425,...,NaN,None,None,D,成长型,契约型封闭式,None,20010904,None,E
1687,500013.SH,基金安瑞,华安基金,中国工商银行,股票型,19920429,20070409,20010830,None,20070410,...,NaN,None,None,D,成长型,契约型封闭式,None,20010830,None,E
1688,500017.SH,基金景业,大成基金,中国农业银行,股票型,19920401,20070115,20011219,None,20070116,...,NaN,None,None,D,成长型,契约型封闭式,None,20011219,None,E
1689,184702.SZ,基金同智,长盛基金,中国银行,股票型,19920313,20070104,20000515,None,20070105,...,NaN,None,None,D,成长型,契约型封闭式,None,20000515,None,E
1690,500028.SH,基金兴业,华夏基金,中国农业银行,股票型,19911115,20060808,20010727,None,20060809,...,NaN,None,None,D,平衡型,契约型封闭式,None,20010727,None,E

In [9]:
# 基金的类型
fund_list.fund_type.unique()

array(['REITs', '股票型', '混合型', '商品型', '债券型', '货币市场型', '另类投资型'],
      dtype=object)

In [11]:
fund_list.columns

Index(['ts_code', 'name', 'management', 'custodian', 'fund_type', 'found_date',
       'due_date', 'list_date', 'issue_date', 'delist_date', 'issue_amount',
       'm_fee', 'c_fee', 'duration_year', 'p_value', 'min_amount',
       'exp_return', 'benchmark', 'status', 'invest_type', 'type', 'trustee',
       'purc_startdate', 'redm_startdate', 'market'],
      dtype='object')

In [42]:
np.nan == np.nan

False

In [58]:
fund_list.filter(['ts_code','fund_type','found_date','list_date','delist_date','m_fee','c_fee','benchmark','invest_type','purc_startdate'])
# .query("benchmark == benchmark")
# .query("delist_date != delist_date")
# status 存续状态D摘牌 I发行 L已上市

,ts_code,fund_type,found_date,list_date,delist_date,m_fee,c_fee,benchmark,invest_type,purc_startdate
0,508058.SH,REITs,20220822,20220831,None,0.19,0.01,None,None,None
1,180501.SZ,REITs,20220822,20220831,None,0.20,0.01,None,None,None
2,508068.SH,REITs,20220822,20220831,None,0.12,0.01,None,None,None
3,159637.SZ,股票型,20220819,20220901,None,0.50,0.05,中证新能源汽车指数收益率,被动指数型,20220901
4,159631.SZ,股票型,20220818,20220826,None,0.50,0.10,中证100指数收益率,被动指数型,20220826
...,...,...,...,...,...,...,...,...,...,...
1686,500019.SH,股票型,19920509,20010904,20070425,1.50,0.25,None,成长型,20010904
1687,500013.SH,股票型,19920429,20010830,20070410,1.50,0.25,None,成长型,20010830
1688,500017.SH,股票型,19920401,20011219,20070116,1.50,0.25,None,成长型,20011219
1689,184702.SZ,股票型,19920313,20000515,20070105,1.50,0.25,None,成长型,20000515
1690,500028.SH,股票型,19911115,20010727,20060809,1.50,0.25,None,平衡型,20010727

In [4]:
df = pro.fund_portfolio(ts_code='001753.OF')

In [ ]:
df.groupby(['ts_code'])

In [5]:
df

,ts_code,ann_date,end_date,symbol,mkv,amount,stk_mkv_ratio,stk_float_ratio
0,001753.OF,20220721,20220630,000408.SZ,13253079.60,402340.0,4.17,0.03
1,001753.OF,20220721,20220630,000625.SZ,13810656.24,797382.0,4.35,0.01
2,001753.OF,20220721,20220630,002176.SZ,18803662.80,750945.0,5.92,0.04
3,001753.OF,20220721,20220630,002192.SZ,15247040.00,99200.0,4.80,0.04
4,001753.OF,20220721,20220630,002459.SZ,22490287.20,285048.0,7.08,0.03
...,...,...,...,...,...,...,...,...
1231,001753.OF,20160328,20151231,300251.SZ,3028545.65,99985.0,2.72,0.01
1232,001753.OF,20160328,20151231,600079.SH,1113000.00,50000.0,1.00,0.00
1233,001753.OF,20160328,20151231,600114.SH,4040000.00,250000.0,3.62,0.10
1234,001753.OF,20160328,20151231,600186.SH,3966820.00,494000.0,3.56,0.05
1235,001753.OF,20160328,20151231,600633.SH,3221813.00,171100.0,2.89,0.02

In [2]:
level_2_index = pro.index_classify(level='L2',src='SW2021')

In [3]:
level_2_index

    index_code industry_name level industry_code is_pub parent_code
0    801016.SI           种植业    L2        110100      1      110000
1    801015.SI            渔业    L2        110200      1      110000
2    801011.SI           林业Ⅱ    L2        110300      0      110000
3    801014.SI            饲料    L2        110400      1      110000
4    801012.SI         农产品加工    L2        110500      1      110000
..         ...           ...   ...           ...    ...         ...
129  801971.SI          环境治理    L2        760100      1      760000
130  801972.SI         环保设备Ⅱ    L2        760200      1      760000
131  801981.SI          个护用品    L2        770100      1      770000
132  801982.SI           化妆品    L2        770200      1      770000
133  801983.SI          医疗美容    L2        770300      0      770000

[134 rows x 6 columns]

In [11]:
index_all

    index_code industry_name level industry_code is_pub parent_code
0    801010.SI          农林牧渔    L1        110000      1           0
1    801030.SI          基础化工    L1        220000      1           0
2    801040.SI            钢铁    L1        230000      1           0
3    801050.SI          有色金属    L1        240000      1           0
4    801080.SI            电子    L1        270000      1           0
..         ...           ...   ...           ...    ...         ...
506  859812.SI          洗护用品    L3        770102      0      770100
507  859821.SI      化妆品制造及其他    L3        770201      1      770200
508  859822.SI         品牌化妆品    L3        770202      1      770200
509  859831.SI          医美耗材    L3        770301      0      770300
510  859832.SI          医美服务    L3        770302      0      770300

[511 rows x 6 columns]

In [2]:
dir(ts)

['MailMerge',
 'TraderAPI',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'bar',
 'bdi',
 'broker_tops',
 'cap_tops',
 'close_apis',
 'codecs',
 'coins',
 'coins_bar',
 'coins_snapshot',
 'coins_tick',
 'coins_trade',
 'day_boxoffice',
 'day_cinema',
 'forecast_data',
 'fund',
 'fund_holdings',
 'futures',
 'get_apis',
 'get_area_classified',
 'get_balance_sheet',
 'get_cash_flow',
 'get_cashflow_data',
 'get_cffex_daily',
 'get_concept_classified',
 'get_cpi',
 'get_czce_daily',
 'get_day_all',
 'get_dce_daily',
 'get_debtpaying_data',
 'get_deposit_rate',
 'get_fund_info',
 'get_future_daily',
 'get_gdp_contrib',
 'get_gdp_for',
 'get_gdp_pull',
 'get_gdp_quarter',
 'get_gdp_year',
 'get_gem_classified',
 'get_gold_and_foreign_reserves',
 'get_growth_data',
 'get_h_data',
 'get_hist_data',
 'get_hists',
 'get_hs300s',
 'get_index',
 'get_industry_classified',
 'get_instrument',
 'get_intlfuture',
 'get_k_data',
 'get_latest_news',
 'get_loan_rate',
 'get_markets',
 'get_money_supply',
 'get_money_supply_bal',
 'get_nav_close',
 'get_nav_grading',
 'get_nav_history',
 'get_nav_open',
 'get_notices',
 'get_operation_data',
 'get_ppi',
 'get_profit_data',
 'get_profit_statement',
 'get_realtime_quotes',
 'get_report_data',
 'get_rrr',
 'get_shfe_daily',
 'get_shfe_vwap',
 'get_sina_dd',
 'get_sme_classified',
 'get_st_classified',
 'get_stock_basics',
 'get_suspended',
 'get_sz50s',
 'get_terminated',
 'get_tick_data',
 'get_today_all',
 'get_today_ticks',
 'get_token',
 'get_zz500s',
 'global_realtime',
 'guba_sina',
 'inst_detail',
 'inst_tops',
 'internet',
 'is_holiday',
 'latest_content',
 'lpr_data',
 'lpr_ma_data',
 'margin_detail',
 'margin_offset',
 'margin_target',
 'margin_zsl',
 'moneyflow_hsgt',
 'month_boxoffice',
 'new_cbonds',
 'new_stocks',
 'notice_content',
 'os',
 'pledged_detail',
 'pro',
 'pro_api',
 'pro_bar',
 'profit_data',
 'profit_divis',
 'quotes',
 'realtime_boxoffice',
 'reset_instrument',
 'set_token',
 'sh_margin_details',
 'sh_margins',
 'shibor_data',
 'shibor_ma_data',
 'shibor_quote_data',
 'stock',
 'stock_issuance',
 'stock_pledged',
 'subs',
 'sz_margin_details',
 'sz_margins',
 'tick',
 'top10_holders',
 'top_list',
 'trade_cal',
 'trader',
 'util',
 'xsg_data']